zazuko/cube-creator

.dockerignore, api.Dockerfile, apis/core/index.ts, apis/core/package.json, apis/core/tsconfig.json, app.Dockerfile, nginx/default.conf, package.json, tsconfig.json
I created docker files for the API and UI.
Separate because I want to avoid the complication of having UI conditionally hosted inside express and build together. In this approach the UI is simply a static nginx container. The API is a node app like before but also made simpler
This time my proposal is to have them deployed like
| What | Where |
| -- | -- |
| API | https://creator.cube |
| UI | https://app.creator.cube |
=> build: set up docker images for app and apis

.editorconfig, .lando.yml, apis/core/bootstrap/cubes.ts, apis/core/bootstrap/entrypoint.ts, apis/core/bootstrap/index.ts, apis/core/hydra/index.ttl, apis/core/index.ts, apis/core/lib/env.ts, apis/core/package.json, apis/core/tsconfig.json, packages/core/namespace.ts, packages/core/package.json, yarn.lock
This is PR brings in a basic read-only capability via hydra-box (actually it's a wrapper on top of hydra-box I build at [hypermedia-app/labyrinth](https://github.com/hypermedia-app/labyrinth); more details in comments).
The core principles are simple: 
1. Every resource `Foo` has its entire contents inside `GRAPH <Foo>` in the triplestore.
1. "Static" or "virtual" resources such as collections or the API entrypoint are also added to the triple store
* they are inserted to the store on app start
2. As much of API behavior as possible is will be controlled by metadata directly in the API Documentation
The API Documentation is right now deployed from filesystem from turtle files in `hydra/` directory
=> feat: first hydra-box resources

.dockerignore, .github/workflows/docker.yaml, api.Dockerfile, app.Dockerfile, tsconfig.json
This is heavily inspired by the [example in the docker/build-push-action](https://github.com/docker/build-push-action#complete-workflow) repo.
It builds two images: `zazuko/cube-creator-{api,app}`. Tags as follow: 
- `sha-{commit}` on every commit
- `edge` for the latest commit on master
- `[branch]` for other branches
- on git tags like `vX.Y.Z`, tags `vX`, `vX.Y`, `vX.Y.Z` and latest
- `pr-X` on pull requests (builds but does not push)
=> Build docker images with GitHub Actions

api.Dockerfile
The Kubernetes manifests have a `runAsNonRoot` policy. But because the user set in the Dockerfile is a username and not a user ID, Kubernetes can't check if that username is not actually `root` without running the image, so it refuses to run the image.
*/me goes fixing his "Docker best practices" doc*
=> Docker/API: use a numeric UID instead of a user name

app.Dockerfile, nginx/default.conf, ui/vue.config.js
That was not really the case, now it is. Please check that the changes in `vue.config.js` do not break the dev environment, I haven't set it up locally.
=> Docker: Serve the app under /app/

api.Dockerfile, app.Dockerfile, ui/package.json, ui/src/components/NavBar.vue, ui/src/router/index.ts, ui/src/store/index.ts, ui/src/store/modules/cube-projects.ts, ui/src/views/Authenticated.vue, ui/src/views/CubeProject.vue, ui/src/views/CubeProjects.vue
Part of #12 
Depends on #19 
I figured it would make easier for other people to continue if I wrote an example of how to use the API.
This PR loads the projects collection and displays a list of projects. The main difference with the data-cube-curation project is that I tried to "embrace" Hydra/Alcaeus more. The API wrapper is way lighter and I do a bit more work in the Vuex store. We'll see how this works out.
I didn't setup any [Alcaeus mixin](https://alcaeus.hydra.how/latest/representations/mixins.html) yet, but that's probably going to make things easier in the next steps.
=> Barebones projects list

ui/src/api/errors.ts
I run into a access of a property of a variable which is null.
details can be null
=> fix: avoid access on property of null

.lando.yml, api.Dockerfile
This adds some logs by default. Having `*` is too verbose (especially because of the healthchecks), but at least having some logs when the app starts is nice.
@tpluscode If you have other log scopes to suggest, please do!
=> Docker: Have some logs by default

.lando.yml, e2e-tests/install-lando.sh
fix #60
Core Container starts only when fuseki is up and running
Healthcheck of fuseki via wget 
(https://stackoverflow.com/questions/47722898/how-to-do-a-docker-healthcheck-with-wget-instead-of-curl)
=> fix: start core after fuseki is stared

ui/vue.config.js
Do not display UI build progress to reduce noise in the lando logs.
=> chore(ui): do not display build progress

apis/core/lib/domain/csv-source/upload.ts, apis/core/lib/domain/queries/csv-source.ts, apis/core/lib/domain/queries/query-client.ts, e2e-tests/csv-source/upload.hydra, ui/src/api/errors.ts, ui/src/views/CSVUpload.vue
fixes #61 
When a file with the same name is uploaded twice an error 409 Conflict is thrown.
To test if this is the case, it is checked if there exists an other CSVSource with the same schema:name.
```TypeScript 
const result = await ASK`
GRAPH ${csvMapping} 
{
${csvMapping} ${cc.csvSource} ?source
}
GRAPH ?source
{
?source ${schema.name} "${fileName}"
}
`
.execute(client.query)
```
I added a new folder structure in domain for sparql queries.
=> feat(csv): error if file added twice to same project

ui/src/components/SidePane.vue
We were not actually using the JS features of bulma-quickview, so we
may as well just load the CSS and avoid any JS issues.
=> fix(ui): bulma-quickview JS error

apis/core/package.json, ui/package.json
Bumping `@cube-creator/ui` and `@cube-creator/core-api` to `0.0.1`, we needed a tag for the initial deployment to the integ environment. I went for [v0.0.1](https://github.com/zazuko/cube-creator/releases/tag/v0.0.1) and it doesn't matter that much at this point as long as we can make sure GitHub Actions picks it up and deploys to integ.
=> chore: bump versions for initial integ deployment

.dockerignore, packages/core/env.ts, packages/core/namespaces/shapes.ts
The `import { shape } from '@cube-creator/core/namespace'` is based in the APIs base URL and hence the namespace builder uses that to initialise. 
I thought to the have this also usable in the VUE app but turns out it does not bundle the env var and it's not available at runtime as I'd hoped.
For now I change that to ignore the base if in the UI, so that the URI will be relative.
=> ENV variable fix in UI build

apis/core/bootstrap/shapes/table.ts, packages/core/namespace.ts, ui/package.json, ui/src/api/index.ts, ui/src/forms/BulmaSelect.vue, ui/src/forms/components.ts, ui/src/views/TableCreate.vue
I implemented the csv source select by directly linking the required `hydra:Collection` on the property.
A little out-of-band, in a better solution this would have been included on a specific instance of shape, directly linked to the table resource.
=> feat: use collection resource to populate dash:InstancesSelectEditor

tsconfig.json, typings/barnard59-core/index.d.ts, typings/rdf-validate-shacl/index.d.ts, ui/package.json, yarn.lock
I removed `skipLibCheck: true` and excluded UI from the root tsconfig. This removed a ton of irrelevant TS "issues" reported by Webstorm's TS support and also revealed small fixes which were required
The only thing was that `@types/jest` conflicted with `@types/mocha`. Thus, I removed `@vue/cli-plugin-unit-jest`. Are we going to use jest in UI project @martinmaillard ?
=> typescript improvements

apis/core/lib/domain/table/csvw.ts, apis/core/test/domain/table/csvw.test.ts, fuseki/sample-ubd.trig, packages/model/Table.ts
With this PR the generated csvw mapping will combine the mapping's `cc:namespace` and table's `cc:identifierTemplate` to create the observation URL
=> feat: use cc:identifier template for csvw:aboutUrl

ui/package.json, ui/src/store/modules/auth.ts, yarn.lock
In private browsing session, Firefox treats localStorage as sessionStorage, meaning that it gets emptied whenever the site is leaved. This is a problem with the oidc-client, because it uses the localStorage to store informations about the current OIDC flow.
This patch changes the state store to use `cookie-storage`, which is a WebStorage-compatible layer on top of cookies.
=> fix: use cookie to store OIDC state

apis/core/lib/middleware/shacl.ts, apis/core/test/middleware/shacl.test.ts
Requests such as `PUT` or especially `PATCH` may not explicitly include a class triple and thus `sh:targetClass` makes no sense for validation. However, without a target no validation happens.
For these scenarios the SHACL middleware will now assume `sh:targetNode` to be the request URI (`req.hydra.term`)
=> fix(shacl): ability to use sh:targetNode to match request URI

package.json
Removing `types` and `bootstrap` from API's coverage. The latter could be unit-tested but I think it makes little sense if any syntax mistake there either brings the entire thing down immediately and other error should be caught by e2e tests
=> ci: exclude some code from coverage

apis/core/lib/domain/csv-mapping/CsvMapping.ts, apis/core/lib/domain/cube-projects/Project.ts, apis/core/lib/domain/cube-projects/create.ts, apis/core/lib/domain/identifiers.ts, apis/core/lib/domain/job/create.ts, apis/core/test/domain/cube-projects/create.test.ts, apis/core/test/domain/job/create.test.ts, fuseki/sample-ubd.trig, packages/model/CsvMapping.ts, packages/model/Job.ts, packages/model/Project.ts
@martinmaillard rightly pointed out that we will have more jobs than just the csv transformation.
For that purpose I am moving the job collection to project resource
=> refactor: move jobs collection to project

ui/src/forms/BulmaSelect.vue, ui/src/views/ColumnMappingCreate.vue
Rather than injecting `sh:in` into the shape to populate the column select we can inject the column labels and their RDF types to have them selected by matching to `sh:class` annotation
=> fix: use `rdfs:Class` for column dropdown

apis/core/bootstrap/shapes/table.ts, apis/core/lib/domain/table/create.ts, apis/core/test/domain/table/create.test.ts, e2e-tests/table/create.hydra
when there is no template the set `{column name 1}/{column name 2}`
fixes #170
=> feat: auto-generated identifier template

ui/package.json, ui/src/lib/expand.ts, ui/src/rdf-properties.ts, ui/src/store/modules/app.ts, ui/vue.config.js, yarn.lock
Removed the need for raw-loader by copying the expand function from `@zazuko/rdf-vocabularies`. ~~Also memoize the properties so that the datasets are not processed every time one hits `loadCommonProperties`~~
=> refactor: re-remove raw-loader and copy expand into a local module

.github/workflows/ci.yaml
Maybe we can combine the jobs to run unit tests and CLI tests to get a single coverage report. This will avoid the bogus code cove comment about coverage drop which sometimes gets updated and sometimes does not when the CLI tests finally arrive
=> ci: combine tests with coverage

ui/src/components/MapperTable.vue, ui/src/components/PropertyDisplay.vue
Display shrunk properties in mapper table instead of full URIs (with full URI in tooltip).
=> feat(ui): display shrunk properties

apis/core/lib/csvw-builder/index.ts, apis/core/test/csvw-builder/index.test.ts, cli/lib/job.ts, cli/lib/pipeline.ts, cli/pipelines/main.ttl, cli/test/lib/commands/transform.test.ts, cli/test/lib/job.test.ts, packages/model/Table.ts, packages/model/lib/Link.ts, ui/src/api/mixins/Table.ts
Some changes required to process observation tables differently from the others:
1. Only observation tables get `/observation` injected into their identifier
2. Only observation tables get the `cc:cube` virtual column
3. Run only plain csvw transformation for table which are not observation tables
=> fix: separate transformation of observation table

apis/core/test/domain/csv-mapping/CsvMapping.test.ts, packages/model/CsvMapping.ts
I know we added a regex to the shape but it may be a good idea anyway to assume that there should a separator after the base.
Also fixes existing projects
=> fix: ensure slash in constructed identifiers

apis/core/lib/csvw-builder/index.ts, apis/core/test/csvw-builder/index.test.ts, cli/lib/output-filter.ts, cli/pipelines/main.ttl, fuseki/sample-ubd.trig
* adding too many suppressed csvw columns
* remove `?foo <#property> ?bar` quads from output. those columns are auto-generated by csvw processor and break Stardog
* add transformation for `cc:language -> csvw:lang`
=> Some small fixes to CSVW et.al.

apis/core/bootstrap/shapes/dataset.ts
Since the list of elements if provided by the in clause, I think the data type is redundant and can be omitted instead of adding all the information that the type can correctly be resolved.
fixes #242
=> fix: remove datatype for frequency

apis/core/package.json, cli/lib/csv.ts, yarn.lock
fixes #267 
Turns out the "quote" string was in fact a bug in the operations which caused a 405 error from the API
At the same time I changed the pipeline to fail fast when the CSV fails to load. This will prevent false positive pipeline runs in the future
=> fix: fail pipeline if csv fails to fetch

apis/core/bootstrap/shapes/csv-source.ts, apis/core/bootstrap/shapes/dataset.ts
A proper fix, followup to #278
Turns out that Stardog's graph store actually hates blank nodes which look like `_:foo_bar` and those a the product of parsing and the serialising again by rdf-ext.
Using hash named nodes removes that problem for good
=> fix: avoid parsing "named" blank nodes

apis/core/bootstrap/shapes/cube-project.ts, apis/core/lib/domain/cube-projects/Project.ts, apis/core/lib/domain/cube-projects/create.ts, apis/core/lib/domain/job/create.ts, apis/core/lib/domain/job/update.ts, apis/core/test/domain/cube-projects/create.test.ts, apis/core/test/domain/job/create.test.ts, apis/core/test/domain/job/update.test.ts, cli/lib/commands/publish.ts, cli/lib/cube.ts, cli/pipelines/publish.ttl, cli/server.ts, cli/test/lib/commands/publish.test.ts, e2e-tests/csv-source/delete.hydra, e2e-tests/csv-source/get-csv.hydra, e2e-tests/csv-source/upload.hydra, e2e-tests/cube-projects/create.hydra, e2e-tests/cube-projects/delete.hydra, fuseki/sample-ubd.trig, packages/core/namespace.ts, packages/model/Job.ts, packages/model/Project.ts, packages/testing/lib/index.ts, typings/barnard59-base/index.d.ts, ui/tests/e2e/specs/project-mapping.spec.ts
This PR should pretty much complete the publishing feature:
1. A "revision" number is appended to cube URIs.
2. When a job completes, the last published revision is incremented on project
3. Cube data is stored at a predefined named graph, stored by project. 
- append and not replace
4. Both the output graph as well the revision are stored with job to allow consistent re-runs
=> Publish cube revisions

cli/lib/commands/publish.ts, cli/server.ts, cli/test/lib/commands/publish.test.ts
I recently renamed the `job` param of the publish command params but failed to realise that it directly maps to the CLI options 😊
=> fix(cli): revert publish command's job param

package.json, yarn.lock
I quickly realised that #286 was in fact flawed because the `0.0.x` range has different resolution rules from `1.x` and `0.x` alike 🙄
=> build(deps): pin barnard59-base

ui/src/views/TableEdit.vue
Reload table from API to avoid submitting a whole bunch of superfluous
quads that are already present in the collection dataset and that failes
validation.
Fixes #306
=> fix(ui): edit table validation

apis/core/lib/ResourceStore.ts, apis/core/lib/csvw-builder/index.ts, apis/core/lib/domain/column-mapping/create.ts, apis/core/lib/domain/column-mapping/delete.ts, apis/core/lib/domain/column-mapping/lib/index.ts, apis/core/lib/domain/column-mapping/update.ts, apis/core/lib/domain/csv-mapping/delete.ts, apis/core/lib/domain/csv-source/delete.ts, apis/core/lib/domain/csv-source/get-head.ts, apis/core/lib/domain/csv-source/update.ts, apis/core/lib/domain/csv-source/upload.ts, apis/core/lib/domain/cube-projects/delete.ts, apis/core/lib/domain/cube-projects/update.ts, apis/core/lib/domain/dataset/update.ts, apis/core/lib/domain/dimension/update.ts, apis/core/lib/domain/job/create.ts, apis/core/lib/domain/job/update.ts, apis/core/lib/domain/table/create.ts, apis/core/lib/domain/table/delete.ts, apis/core/lib/domain/table/update.ts, apis/core/test/domain/column-mapping/delete.test.ts
This changes the default of `ResourceStore` to throw when a resource is not found. A second parameter can be added where an `undefined` is acceptable. Types adjust automatically which removes the need to the repetitive `if (!resource) throw new Error()` boilerplate
=> refactor: throw on not found resources by default

apis/core/lib/domain/csv-mapping/CsvMapping.ts, apis/core/lib/domain/cube-projects/Project.ts, apis/core/lib/domain/cube-projects/update.ts, apis/core/lib/domain/dataset/Dataset.ts, apis/core/lib/domain/dimension/DimensionMetadataCollection.ts, apis/core/test/domain/cube-projects/update.test.ts
When a project update changes the `cc:namespace` the cube should also be updated
=> fix: rename cube when namespace changes

ui/src/components/JobForm.vue, ui/src/store/modules/api.ts, ui/src/views/ColumnMappingCreate.vue, ui/src/views/ColumnMappingEdit.vue, ui/src/views/CubeMetadataEdit.vue, ui/src/views/CubeProjectCreate.vue, ui/src/views/CubeProjectEdit.vue, ui/src/views/DimensionEdit.vue, ui/src/views/SourceEdit.vue, ui/src/views/TableCreate.vue, ui/src/views/TableEdit.vue, ui/tests/e2e/specs/project-mapping.spec.ts
Replace full-blown "message" by simple toasts for notifications after a successful operation.
Fixes #341
=> feat(ui): use toasts for success messages

apis/core/bootstrap/shapes/dataset.ts
Jeremy Stucky found an error 
There was `dcterms:comment` instead of `dcterms:description`
Don't ask me where this came from...
=> fix: dcterms:descritption instead of comment

apis/core/lib/domain/dataset/update.ts, apis/core/test/domain/dataset/update.test.ts
The dataset metadata update endpoint was all too eager to save anything it received.
This PR changes this so that only saved quads will be those which has the dataset for subject and blank node children.
Specifically, any pre-existing triples about `<dataset> schema:hasPart ?cube` will be left intact
=> fix: more selectively accept dataset metadata

cli/index.ts
We've stopped seeing CLI logs in Sentry, likely due to a the process ending too abruptly, according to @sandhose. (see https://docs.sentry.io/platforms/node/configuration/draining/)
This adds a timeout to give sentry time to write the logs before `process.exit`
=> fix(cli): process.exit blocks sentry logs

apis/core/lib/handlers/table/create.ts, apis/core/lib/handlers/table/update.ts, packages/core/namespace.ts, ui/src/components/LiteralColumnMappingForm.vue, ui/src/store/modules/project.ts, ui/src/store/serializers.ts, ui/src/views/ColumnMappingCreate.vue, ui/src/views/ColumnMappingEdit.vue, ui/src/views/TableCreate.vue, ui/src/views/TableEdit.vue
Do not refresh whole UI when adding/updating stuff. Currently only implemented for critical operations: add/update table and add/update column mapping.
Fixes #335
=> Avoid refreshing whole UI

cli/lib/csv.ts
For some reason the pipelines failed on gitlab when they get to parsing the CSV
I appears that they get XML from S3 which might indicate that something is off about the download link...
=> fix(cli): add more logging to transformation pipeline

ui/src/components/JobForm.vue, ui/src/components/JobIcon.vue, ui/src/components/JobItem.vue, ui/src/components/PageContent.vue, ui/src/components/TransformJobButton.vue, ui/src/router/index.ts, ui/src/store/modules/project.ts, ui/src/views/CubeProject.vue, ui/src/views/Publication.vue
Will fix #378 
- Adds a main, always visible, "transform" button
- Adds a way to see previous transform jobs
- Polls jobs to display "real-time" status of jobs
- Transform "Pipeline" page into "Publication" page: shows only publication-related jobs
Warning: it will break dev because the new button doesn't allow providing the required Github Token when starting a job
=> Main "transform" button

apis/core/lib/domain/csv/index.ts, apis/core/test/domain/csv/parse.test.ts
fixes #255
BOM was not parsed correctly when extracting column names from CSV, and it ended up as an invisible character in the first column name. Hence, it would not match those coming from `csv-parser`
=> fix: assume BOM when parsing to get header names

cli/lib/commands/publish.ts
fixes #395 
By setting an environment variable `PUBLISH_GRAPH_OVERRIDE` all published cubes will be written there and not to the project's usual target
=> feat(publish): add override to publish to a different graph

apis/core/hydra/projects.ttl, apis/core/lib/domain/queries/cube-data.ts, apis/core/lib/handlers/cube-data.ts, ui/src/components/TermDisplay.vue, ui/src/views/ResourcePreview.vue
Display properties of a resource in Cube Preview.
One thing left to fix: the endpoint seems to load all cube data in memory, which makes it really slow. It's not related to the code of the handler (I tried with an empty handler).
Will close #358
=> feat: cube resource preview

apis/core/lib/domain/queries/cube.ts, cli/lib/output-filter.ts, cli/pipelines/main.ttl, cli/pipelines/publish.ttl, cli/test/lib/commands/publish.test.ts, cli/test/lib/commands/transform.test.ts
If we don't find a better query to improve `loadCubeShapes`, this would fix #402 
**Problem**
The problem is that we want to fetch only the shapes from the generated cube graph but that graph contains many more triples: other cube metadata, observations, and mapped resources which are not observations
To exclude everything but the shape is not trivial because the shapes is heavy with blank nodes and rdf lists. A property path would work to get shape's subgraphs but support in Stardog appears buggy.
**Solution**
The way around it is to keep the `[] csvw:describes ?row` triples which allow removing everything which was mapped from CSV. That triple will then be removed for good when publishing.
=> fix: performance of /dataset

README.md, apis/core/lib/handlers/csv-source.ts, apis/core/lib/handlers/cube-projects.ts, apis/core/lib/handlers/dataset.ts, apis/core/lib/handlers/dimension.ts, apis/core/lib/handlers/table/create.ts, apis/core/package.json, apis/core/test/middleware/operations.test.ts, apis/core/test/middleware/resource.test.ts, apis/core/types/hydra-box/index.d.ts, package.json, yarn.lock
This will improve the performance of API requests by optimising the loading of resources:
1. `hydra-box`/`labyrinth` only loads minimal triples necessary to find operations and not entire graphs
- complete representation available as `async req.hydra.resource.dataset()`, `req.hydra.resource.quadStream()` and `async req.hydra.resource.clownface()`
2. `labyrinth` combines what previously was multiple queries into a single SELECT to reduce SPARQL round-trips
=> Update hydra-box and labyrinth

ui/src/store/modules/projects.ts, ui/src/store/serializers.ts, ui/src/views/CubeProjects.vue
Will fix #406 
Display organization and cube identifier in projects list. I could not display the creator yet because we don't store the user name (c.f. #158)
=> feat(ui): display more infos in projects list

ui/src/components/MapperTable.vue
Do not completely break when a table contains a link to another that doesn't exist
=> fix(ui): handle broken table link

cli/lib/cube.ts, cli/lib/metadata.ts, cli/lib/variables.ts, cli/test/lib/commands/publish.test.ts, packages/testing/lib/chaiShapeMatcher.ts
The problem was that the pipeline looked up metadata by wrong identifiers, because of cube revision being injected into the URIs
This went unnoticed because the shape check returned false positive when there was nothing to validate in the input pointer.
=> fix: dimension metadata not published

ui/src/components/CubePreview.vue, ui/src/components/CubePreviewValue.vue, ui/src/store/modules/project.ts, ui/src/views/CubeDesigner.vue, ui/src/views/ResourcePreview.vue
When clicking on a linked resource in the cube preview, it opens up a pane to preview the resource properties. If these properties contain links to other resources, it is now possible to also click on them to preview the linked resource.
As a side-effect, this will also fix #289
=> Support multi-level linked resources in cube preview

cli/README.md, cli/package.json
I removed `--to` from the script, as the readme says. Keep that in min if you used that script locally
=> chore: added command to run publication locally

cli/lib/output-filter.ts, cli/package.json, cli/pipelines/main.ttl, cli/test/lib/commands/transform.test.ts
Changing the filter pipeline steps to exclude all `csvw:` triples from transformed observation tables. Still keeps `csvw:describes` for non-observation tables.
This fixes a strange behaviour which causes the first row of some CSV files be transformed into a blank node. Since we need the `csvw:describes` only for non-observation tables, this is fine.
=> fix: kill blank node observation

ui/src/components/CsvSourceMapping.vue
When creating multiple tables from the same CSV source, it's really annoying that the selected columns stay selected after creating a table. This PR fixes that by unselecting the columns on route change.
=> feat(ui): unselect table columns on route change

ui/src/main.ts
When an error is intercepted by Sentry, it is not logged in the console by default. It makes debugging a bit harder. This option will log errors in the console.
=> chore(ui): log errors in console

ui/src/components/CubePreview.vue
Make the Cube Preview loader take the same height as the loaded
observations to keep all the UI controls in place while loading the next
page.
=> feat(ui): improve cube preview loader height

ui/src/views/ResourcePreview.vue
Remove warning about the resource preview being slow. It's not anymore :) (cf #399)
=> chore(ui): remove "slow resource preview" warning

ui/src/forms/editors/IdentifierTemplateEditor.vue, ui/src/forms/editors/index.ts
Do not auto-complete identifier template if "is observation table" is selected. We want to encourage users to let us generate identifiers for observations.
=> fix(ui): no identifier autocomplete on observation table

apis/core/lib/domain/queries/column-mapping.ts
We check if a property is used by an other table before deleting the dimension metadata.
This is wrong since we only handle metadata for observation tables.
This PR checks that we only keep a dimension if it is used by an other observation table.
fixes #438
=> fix: only check observation tables for used dimensions

apis/core/lib/domain/queries/column-mapping.ts, apis/core/lib/domain/table/delete.ts, apis/core/test/domain/column-mapping/delete.test.ts, apis/core/test/domain/table/delete.test.ts, apis/core/test/domain/table/update.test.ts
When a table to delete has any referencing column mappings, this mapping should also be deleted to avoid orphaned column mappings.
fixes #425
=> feat: when deleting table delete all mappings referencing this table

apis/core/bootstrap/shapes/dimension.ts, apis/core/hydra/dimension-mapping.ttl, apis/core/lib/domain/dimension-mapping/DimensionMapping.ts, apis/core/lib/domain/queries/dimension-mappings.ts, apis/core/lib/handlers/dimension-mapping.ts, apis/core/test/domain/dimension-mapping/DimensionMappings.test.ts, apis/core/test/domain/queries/dimension-mappings.test.ts, apis/core/test/handlers/dimension-mapping.test.ts, fuseki/sample-ubd.trig
This PR ensures that all unmapped values found in `cube:Observation` and `cube:Constraint` are dynamically added to the mappings dictionary when GETing the resource.
The individual entries repeat the link to the dimension so that is can be queried from the editor using `hydra:search` annotation.
=> feat: getting dimension mappings ensure all values

ui/src/components/CubePreview.vue, ui/src/components/CubePreviewDimension.vue, ui/src/components/TermWithLanguage.vue
Instead of just saying "Missing dimension name", say "Missing name for year".
=> feat(ui): show dimension property when missing name

.changeset/heavy-geese-kneel.md, apis/core/lib/csvw-builder/index.ts, apis/core/test/csvw-builder/index.test.ts, cli/package.json, yarn.lock
Turns out `cc:defaultValue` was completely ignored when building the CSVW. This PR fixes that.
Now I looked at https://github.com/rdf-ext/rdf-parser-csvw and I'm pretty sure it's not handling `csvw:default` either...
Related to #345 
[UPDATE] I submitting [a PR to add support for `csvw:default` to `rdf-parser-csvw`](https://github.com/rdf-ext/rdf-parser-csvw/pull/31)
=> fix: apply csvw.default when available

ui/src/store/modules/auth.ts
The session monitoring sometime triggered a race condition where the auth server notified a session change, which made the OIDC client silently re-check the session, but with the wrong scopes.
The hardcoded scope can be seen here: https://github.com/IdentityModel/oidc-client-js/blob/e7093cf17cfa006036066bcae27f7728fafe8419/src/UserManager.js#L334
This disables the session monitoring. It was there to trigger app logouts when the user logs out from the auth server but not from within the app. I think we can live without that :)
This should fix #480
=> Disable OIDC session monitoring

.changeset/cold-knives-love.md, ui/src/components/HydraOperationError.vue, ui/src/components/HydraOperationForm.vue
Part of #175
This PR doesn't fully solve the issue, but it makes the following improvements:
- Display field labels instead of property paths for invalid fields
- Don't display "the request doesn't conform to SHACL blabla"
- Take less space to display information and make it easier to read.
Screenshot:
=> feat(ui): improve form validation messages

apis/managed-dimensions/hydra/index.ttl, apis/managed-dimensions/lib/domain/managed-dimension.ts, apis/managed-dimensions/lib/handlers/managed-dimension-term.ts, apis/managed-dimensions/lib/handlers/managed-dimension.ts, apis/managed-dimensions/lib/handlers/resource.ts, apis/managed-dimensions/lib/shapes/managed-dimension-term.ts, apis/managed-dimensions/test/lib/domain/managed-dimension.test.ts, apis/managed-dimensions/test/lib/shapes/index.test.ts, e2e-tests/managed-dimensions/term-set.hydra, e2e-tests/managed-dimensions/term.hydra, fuseki/managed-dimensions.trig, packages/core/namespace.ts
Reintroduce `md:ManagedDimension(Term)` types to separate API operations from external `meta:SharedDimension`
=> fix: ensure external dimensions do not have PUT/DELETE operations

apis/core/package.json, apis/managed-dimensions/package.json, cli/package.json, packages/express-rdf-request/package.json, packages/model/package.json, packages/shacl-middleware/package.json, packages/testing/package.json, ui/package.json
`"*"` ranges prevent automatic version bumps when a dependency changes in the monorepo
=> build: use proper version ranges between packages

apis/shared-dimensions/hydra/index.ttl
The "DELETE" buttons were still present on external dimensions
=> fix(fix): actually remove DELETE from external shared dimensions

apis/shared-dimensions/lib/store.ts, apis/shared-dimensions/test/lib/loader.test.ts, apis/shared-dimensions/test/store.test.ts, fuseki/shared-dimensions.trig
Detaches the shapes describing resource and uses `sh:targetNode` to relate it to said resource.
Run this to update live DB
```sparql
PREFIX sh: <http://www.w3.org/ns/shacl#>
with <https://lindas.admin.ch/cube/dimension> 
delete {
?resource sh:node ?shape
} 
insert {
?shape sh:targetNode ?resource
}
where { 
?resource sh:node ?shape
}
```
=> refactor: reverse relation shape describing resources

.changeset/cool-jeans-wonder.md, .changeset/fifty-doors-deliver.md, apis/core/index.ts, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/shapes/shared-dimension-term.ts, apis/shared-dimensions/lib/shapes/shared-dimension.ts, apis/shared-dimensions/lib/store.ts, apis/shared-dimensions/package.json, apis/shared-dimensions/test/lib/domain/managed-dimension.test.ts, apis/shared-dimensions/test/lib/shapes/index.test.ts, apis/shared-dimensions/test/support/store.ts, e2e-tests/shared-dimensions/term-set.hydra, e2e-tests/shared-dimensions/term-sets.hydra, e2e-tests/shared-dimensions/term.hydra, fuseki/shared-dimensions.trig
Add `dcterms:identifier` to be used to generate term (set) URIs. (only lowercase, number and hyphen)
Will respond 409 if another term (Set) with the generated URI already exists.
Is it a little weird to have both `dcterms:identfier` and `schema:identifier`? 🤷
=> fix: shared dimension idnetifier

.changeset/tasty-snails-roll.md, ui/src/views/CubeProject.vue
I don't really understand why the error never reaches `App.errorCaptured`, but it probably has to do with the fact that the code is async.
Anyway, this change will just stop polling jobs if any error occurs. This should solve our Sentry overflow issue.
=> fix(ui): stop polling jobs on API error

.changeset/dirty-kids-smell.md, ui/package.json, ui/src/main.ts, yarn.lock
This tells the Sentry SDK to send trace ID headers when doing requests to the API, allowing for distributed traces.
This is waiting on a small patch in alcaeus by @tpluscode hence the draft
=> feat: propagate Sentry traces between UI and API

apis/core/package.json, apis/shared-dimensions/package.json, cli/package.json, packages/model/package.json, packages/testing/package.json, ui/package.json
Re: https://github.com/atlassian/changesets/issues/544
This ensures that version of dependent packages are bumped when pinned dependencies are updated
=> build: pin versions to have them bumped on upstream changes

.changeset/cool-flowers-clap.md, .changeset/mighty-ligers-bake.md, apis/core/lib/domain/dataset/update.ts, apis/core/test/domain/dataset/update.test.ts, ui/src/graph.ts, ui/src/views/CubeMetadataEdit.vue
This fixes some problems with unexpected quads being stored in the cube meta graph when saving
1. The UI will only load the correct quads in the form
2. The API will actually replace the graph with only the quads coming from the request
=> fix: superfluous quads in cube metadata graphs

.changeset/heavy-jokes-greet.md, ui/src/views/DimensionEdit.vue
Dimension metadata was apparently saved in the cube graph instead of the dimension metadata collection graph. I don't understand why it looked like it was working, but this PR may fix a bunch of stuff.
Fixes #646
=> fix(ui): dimension metadata saved in wrong graph

.changeset/quiet-crabs-fix.md, cli/lib/commands/publish.ts, cli/lib/commands/transform.ts, cli/lib/upload.ts, cli/lib/variables.ts, cli/package.json, cli/pipelines/publish.ttl, yarn.lock
Instead of streaming directly to the endpoint, a temporary file is created first and uploaded separately once transformation if done. If the upload fail, there will be two more attempts made
fixes #628 
likely will also improve #563
possibly could also help with #586, if the problem was indeed the time it would take to transmit the triples
=> fix(cli): write output to temporary file

.changeset/fuzzy-geese-promise.md, cli/lib/hydra-cache.ts
Right now we do not fetch any resource twice to prevent unnecessary API requests
This PR makes an exception for the `CSVSource` class, which provides the s3 link. Now every time a CSV is downloaded, a fresh link will be used
=> fix(cli): fetch CSV Source every time to get new s3 links

.changeset/cyan-garlics-chew.md, .local.env, apis/core/README.md, apis/core/lib/domain/job/create.ts, apis/core/lib/domain/job/update.ts, apis/core/test/domain/job/create.test.ts, apis/core/test/domain/job/update.test.ts, fuseki/sample-ubd.trig, packages/core/env.ts, packages/model/Job.ts, ui/src/components/ExternalResource.vue, ui/src/components/JobItem.vue, ui/src/store/serializers.ts, ui/src/views/Publication.vue
Extends the details of publish jobs:
- version (will show for existing jobs)
- status
- "publish to"
- link to a Lindas query (only when job succeeds)
"status" and "publish to" actually dereference to show `schema:name`
The Lindas query is indirect, searching by the parent cube and version rather than concrete URI. Like below:
```sparql
PREFIX schema: <http://schema.org/>
describe ?cube
from <https://lindas.admin.ch/foen/cube>
where {
<https://environment.ld.admin.ch/foen/faostat-prod_test001> schema:hasPart ?cube .
?cube schema:version 4 .
}
```
Partially addresses #651
=> feat: more details on job list

.changeset/grumpy-forks-jump.md, .local.env, apis/core/bootstrap/entrypoint.ts, apis/core/index.ts, apis/shared-dimensions/README.md, apis/shared-dimensions/bootstrap/entrypoint.ts, apis/shared-dimensions/bootstrap/index.ts, apis/shared-dimensions/bootstrap/termSetCollections.ts, apis/shared-dimensions/hydra/index.ttl, apis/shared-dimensions/index.ts, apis/shared-dimensions/lib/domain/shared-dimension-term.ts, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/domain/shared-dimensions.ts, apis/shared-dimensions/lib/env.ts, apis/shared-dimensions/lib/handlers/shared-dimension-term.ts, apis/shared-dimensions/lib/handlers/shared-dimension.ts, apis/shared-dimensions/lib/handlers/shared-dimensions.ts, apis/shared-dimensions/lib/middleware/shacl.ts, apis/shared-dimensions/lib/namespace.ts, apis/shared-dimensions/lib/rewrite.ts, apis/shared-dimensions/package.json, apis/shared-dimensions/test/lib/domain/managed-dimension.test.ts, e2e-tests/shared-dimensions/term-set.hydra, e2e-tests/shared-dimensions/term-sets.hydra, e2e-tests/shared-dimensions/term.hydra, e2e-tests/shared-dimensions/terms.hydra, fuseki/shared-dimensions.trig, packages/shacl-middleware/index.ts, yarn.lock
This attempts to completely hide the API URL and the shared dimension terms. All resources will be stored as `ld.admin.ch/cube/dimension` but the API will rewrite those URLs for the purpose of client-server communication
Uses `camouflage-rewrite` to but requests have to be manually rewritten in our code (see https://github.com/zazuko/camouflage-rewrite/issues/2)
=> refactor: rewrite API urls to have correct namespace in db

.changeset/plenty-keys-develop.md, apis/core/lib/handlers/dimension-mapping.ts, apis/core/test/handlers/dimension-mapping.test.ts, cli/lib/output-mapper.ts
#690 introduced a change that the shared dimensions are store using a different base URI that the hosted API.
Consequently it is also necessary to apply same namespace replacement in the Cube Creator core so that dimension mapping dictionaries are saved using the correct, canonical namespace, and later output like that from the transformation pipeline
=> feat: separate dimension namespace

.changeset/gentle-waves-battle.md, apis/core/hydra/job.ttl, apis/core/lib/domain/job/create.ts, apis/core/lib/handlers/jobs.ts, apis/core/lib/pipeline/trigger.ts, cli/server.ts, e2e-tests/jobs.hydra, packages/core/namespace.ts, packages/model/ImportJob.ts
This adds another operation to the API, which creates a job of a new type `ImportJob` and triggers it to run
Part of #79
=> feat: ImportJob class and API

.changeset/green-glasses-matter.md, cli/.test.env, cli/lib/commands/publish.ts, cli/lib/cube.ts, cli/lib/metadata.ts, cli/lib/variables.ts, cli/package.json, cli/pipelines/publish.ttl, cli/test/lib/commands/publish.test.ts, cli/test/lib/cube.test.ts, fuseki/sample-ubd.trig
re https://github.com/visualize-admin/visualization-tool/issues/80#issuecomment-840374218
This improves how the previous versions are expired with `schema:validThrough`
The current implementation simply adds a triple where the subject is created as `/${version - 1}` but that falls short if the next version published shall skip a number for whatever reason.
Instead, the published store will be queried to find unversioned cubes of the given cube series, and set validity to all of them
=> fix(cli): setting expiry of previous cubes

ui/src/forms/FormProperty.vue
`VueMarkdown` does not refresh content from slot, which can be a problem for dynamically shown/hidden properties. 
Using property binding helps
=> fix(ui): property description not updated

packages/model/Project.ts
I don't know why this `isCsvProject` fails in the TEST publish pipeline. Might as well align with how the UI determines project kind anyway
=> refactor: different check for CSV project

.changeset/short-snakes-serve.md, ui/src/components/ExternalTerm.vue
Should fix https://github.com/zazuko/cube-creator/issues/731
=> fix(ui): switch language for resource labels

.changeset/weak-pants-double.md, apis/core/bootstrap/shapes/dataset.ts, cli/lib/import/cubeMetadata.ts, cli/package.json, cli/test/lib/commands/import.test.ts, yarn.lock
We have some cube meta properties which are hidden in the form UI, and required to mirror value of another predicate
This PR ensures that when importing a cube, we construct the mirrored values, thus preventing confusing validation errors in the APP
=> fix(import): import mirrored cube meta properties

.changeset/hip-comics-worry.md, apis/core/lib/domain/cube-projects/update.ts, apis/core/lib/handlers/cube-projects.ts, e2e-tests/cube-projects/update.hydra
I broke updating csv projects by calling the `exists` check unnecessarily
=> fix(api): update project without changing identifier

.changeset/many-walls-kick.md, apis/shared-dimensions/lib/rewrite.ts, apis/shared-dimensions/lib/shapes/shared-dimension.ts, apis/shared-dimensions/lib/store.ts, apis/shared-dimensions/package.json
1. Rewrite any blank nodes in resources as `urn:shape:...`
2. Do not use blank nodes in extracted shapes
This could mitigate some of the issues we've been having with synchronisation between cluster nodes
=> refactor: no blanks in shared dimensions

.changeset/shiny-bats-train.md, ui/src/components/CubePreview.vue, ui/src/views/CubeDesigner.vue
If the Cube Designer was opened before the cube had any dimension (if a
job is running for example), refreshing the data would not display
observations properly. It will now refresh the dimensions if needed.
=> fix(ui): refresh cube dimensions when needed

ui/src/App.vue, ui/src/components/auth/SignOutButton.vue, ui/src/store/modules/auth.ts
Follow-up to #768 
Clearing the state on logout wasn't a great idea because users don't usually use the logout button. This will clear the state without requiring any user action.
Should help with #767
=> fix(ui): clear stale OIDC cookies on login

.changeset/quick-melons-lick.md, cli/lib/metadata.ts
I don't understand why, but somehow the timing as off here, and the code which would emit the `schema:version` came too early, when the dimensions to version were not yet determined.
By moving it to the flush callback, we can wait for the entire stream to pass and only then push these quads
=> fix(publish): emit dimension versions at end of stream

.changeset/nasty-brooms-wash.md, apis/core/lib/domain/queries/cube.ts, apis/core/lib/handlers/dataset.ts
I completely rewrote the query which loads the cube/shape/properties for the `/dataset` resource
Now it is done in 2 separate queries which are much faster combined than the previous, especially for large cubes.
=> fix: improve queries for /dataset resource

.changeset/forty-penguins-add.md, ui/src/forms/editors/AutoCompleteEditor.vue
Prevents the selected option from being replaced by its URI
This happens because the select box search text was cleared, causing it to run a query again, with empty string. Because there is no explicit "display value" property, this means that the selected item would not appear in the retrieved items
The change is to prevent the "empty search" and only allow it on the initial load
=> fix(ui): do not "lose" selected shared term

.changeset/lemon-roses-promise.md, cli.Dockerfile, cli/lib/commands/runner.ts, cli/package.json, yarn.lock
In the end, handling the `unhandledRejection` event serves the purpose of actually ending the process gracefully and marking the job resource as failed
Thus, the `--unhandled-rejections=strict` flag and newer version of `sparql-http-client` are unnecessary but won't hurt either. I can revert...
=> Unhandled rejections should fail job

.changeset/neat-pears-notice.md, apis/core/lib/domain/queries/dimension-mappings.ts
Breaking up the query so that cube data graph is determined first. The use `FROM` instead of `GRAPH`
Removing the `DISTINCT` does not appear to improve much but still are redundant
=> Shared dimension mapping: improve loading time

.changeset/hip-jobs-switch.md, apis/shared-dimensions/index.ts, apis/shared-dimensions/lib/handlers/shared-dimension-term.ts, apis/shared-dimensions/lib/handlers/shared-dimensions.ts, apis/shared-dimensions/lib/middleware/canonicalRewrite.ts, apis/shared-dimensions/package.json, ui/src/store/serializers.ts, ui/src/store/types.ts, ui/src/views/SharedDimension.vue, yarn.lock
I am not stoked about this.
Because `camouflage-rewrite` replaces all occurrences of the `ld.admin` URIs from the responses, I had to add a maimed URI as the "canonical" and fix it back on the UI so that it does not get replaced with local API identifiers like the rest of it...
=> fix(ui): showing correct term URI

.lando.yml, .local.env, e2e-tests/cube-projects/create-invalid.hydra, e2e-tests/install-lando.sh, fuseki/sample-px.trig, fuseki/sample-ubd.trig
At long last, an update to lando finally allows the proxied hosts to be used for all inter-service communication nada without using ports
This potentially breaking change came in a patch release, because why not.
=> build: update lando

.changeset/rich-parrots-decide.md, .github/workflows/docker-api.yaml, .github/workflows/docker-app.yaml, .github/workflows/docker-cli.yaml
Due to some limitations of Docker Hub, we switch to the GitHub Container Registry.
=> Switch to GHCR

apis/core/hydra/csv-source.ttl, apis/core/lib/domain/csv-source/replace.ts, apis/core/lib/handlers/csv-source.ts, apis/core/lib/upload.ts, apis/core/test/domain/csv-source/replace.test.ts, e2e-tests/csv-source/replace.hydra, ui/src/store/modules/project.ts, ui/src/styles/utilities.scss, ui/src/views/CSVReplace.vue
Implements the same mechanism as #794 for the "replace CSV file" feature. I didn't add a changeset because the main feature hasn't been released yet.
I think it won't cause a memory issue, but we'll see when we deploy...
=> feat: handle large files when replacing CSV file

.changeset/silent-trainers-teach.md, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/handlers/shared-dimension.ts, apis/shared-dimensions/lib/handlers/shared-dimensions.ts
While working on #814 I noticed that `md:terms` was getting persisted with the data which should not have been the case (was meant to be removed, being listed in `sh:ignoredProperties`)
The reason was that the actual shape would not have been loaded (`hydra:expect` Is obviously just the identifier 🤦)
And there was also a type, which is how I noticed...
=> fix: `md:terms` property should not have been saved

.changeset/new-badgers-leave.md, apis/core/bootstrap/organizations.ts, apis/core/bootstrap/shapes/dataset.ts, apis/core/hydra/organization.ttl, cli/lib/commands/publish.ts, cli/lib/metadata.ts, cli/lib/variables.ts, cli/test/lib/commands/publish.test.ts, packages/model/Cube.ts, packages/model/Organization.ts
Adds `schema:dataset` to organisation profile
When present, its value will be published to link the void resource to cube with "Published" status
=> feat(publish): add link void dataset link to published cubes

.changeset/thin-walls-shake.md, cli/lib/cube.ts, cli/test/lib/commands/publish.test.ts
`schema:expires` is semantically more correct.
Part of #821
=> Switch schema:validThrough -> schema:expires for cubes

.changeset/silver-olives-hug.md, apis/shared-dimensions/lib/middleware/shacl.ts, e2e-tests/shared-dimensions/term-set.hydra
Validation would not happen because the SHACL middleware looked for the shapes using wrong identifiers
The y need to be mapped from the canonical namespace (ld.admin.ch) to API namespace, similarly to he reverse done in `getTargetNode`
=> fix: validation shared dimension requests

.changeset/silent-oranges-worry.md, apis/core/lib/domain/csv-source/CsvSource.ts, apis/core/lib/domain/csv-source/replace.ts, packages/model/CsvSource.ts, ui/src/components/CsvSourceMapping.vue, ui/src/store/serializers.ts
When we import, we add an error message to the CSV Sources.
If an error was already set the mapping screen would fail to load (the property wanted only one error)
=> fix: display all csv errors

.changeset/beige-ads-jump.md, apis/core/lib/domain/cube-projects/queries.ts, apis/core/lib/domain/dataset/update.ts, apis/core/test/domain/dataset/update.test.ts, cli/lib/metadata.ts, cli/test/lib/commands/publish.test.ts, packages/model/Organization.ts
Maintainer and creator organization can be different. But the SPARQL endpoint to retrieve a published cube must come from the maintainer, since it's the one used when publishing.
Fixes #852
=> Get SPARQL/query endpoints from maintainer instead of creator

.changeset/good-spoons-sneeze.md, .changeset/silent-rats-shake.md, .local.env, apis/core/lib/domain/job/create.ts, apis/core/lib/domain/job/update.ts, apis/core/test/domain/job/create.test.ts, apis/core/test/domain/job/update.test.ts, cli/lib/metadata.ts, cli/test/lib/commands/publish.test.ts, fuseki/sample-ubd.trig, packages/core/env.ts, packages/core/namespace.ts, packages/model/Job.ts, ui/src/store/modules/app.ts, ui/src/views/Publication.vue, ui/src/views/SharedDimension.vue, ui/src/views/SharedDimensions.vue
=> Provide dataset workExamples

cli/index.ts, cli/lib/commands/timeoutJobs.ts, cli/lib/job.ts, cli/package.json, cli/test/lib/commands/timeoutJobs.test.ts
Quick changes to the jobs timeout CLI
1. do not overwrite the original job link (does not make sense to link to the "expire jobs" run)
2. run sequentially to prevent all updates requesting its own auth token
3. push a generic error message
4. make sure logging is enabled
=> Expire jobs - improvements

.changeset/tough-trees-fetch.md, cli/lib/cube.ts, cli/test/lib/commands/publish.test.ts, cli/test/lib/commands/unlist.test.ts, fuseki/sample-ubd.trig
As mentioned in #821, the `schema:expires` should be set depending on the status of published cube
- Publishing a "Published" cube does expire all former cubes.
- Publishing a "Draft" does expire all former "Draft" cubes and does not touch the "Published" cube.
Until now all cube would have been expired regardless of the status. This PR fixes that
=> fix: expire cubes correctly based on cube status

.changeset/chilly-comics-punch.md, apis/core/lib/ResourceStore.ts, apis/core/lib/domain/column-mapping/delete.ts, apis/core/lib/domain/table/delete.ts, apis/core/test/domain/column-mapping/delete.test.ts
Until now it would throw when column mapping was not found
=> fix: delete project, missing column mapping

.changeset/purple-crews-argue.md, .changeset/weak-colts-judge.md, apis/core/bootstrap/shapes/cube-project.ts, apis/core/lib/domain/cube-projects/import.ts, apis/core/test/domain/cube-projects/import.test.ts
Related to #878, I realised that when a different organisation is selected, the cube and dimension URIs are not corrected.
This PR fixes that and also adds the ability to change the identifier, being the other configurable component of the cube URIs
=> fix: importing project must correct cube URIs

.changeset/spicy-shirts-boil.md, cli/lib/commands/runner.ts, cli/lib/commands/transform.ts, cli/lib/counters.ts, cli/lib/csv.ts, cli/lib/job.ts, cli/lib/variables.ts, cli/pipelines/main.ttl, fuseki/sample-ubd.trig, ui/src/api/index.ts, ui/src/views/Job.vue
As the transformation job runs, this inspects the `csvw:rownum` quads and keeps track of where in the CSV the pipeline is at any given moment
In case of an error, this information is added to the job and displayed in the UI
=> feat: track last transformed row

.changeset/heavy-laws-reply.md, apis/core/index.ts, apis/core/lib/Loader.ts
Extends and reimplements the `forPropertyOperation` method of [SparqlQueryLoader](https://github.com/hypermedia-app/creta/blob/v0.4.1/lib/loader.ts#L71-L104)
By splitting the query in two we will greatly reduce the load times. In an example project the cut is from 3s to around 150 ms total
=> fix: optimize loading of property operations

.changeset/seven-moose-develop.md, apis/core/lib/csvw-builder/index.ts, apis/core/test/csvw-builder/index.test.ts, cli/lib/output-mapper.ts, cli/pipelines/main.ttl, cli/test/lib/commands/transform.test.ts, packages/model/lib/uriTemplateParser.d.ts, packages/model/lib/uriTemplateParser.js, packages/model/package.json, packages/model/test/lib/uriTemplateParser.test.ts, yarn.lock
This will replace incomplete referenced URIs with `cube:Undefined` if any referenced column is empty
To do that, a regular expression will be added to the CSVW columns. For example, a template `/resource/{NAME}/{ID}` will add a regex pattern `^/resource/.+/.+$` (will actually include the full domain)
This way, transformed values for the column's property which do not satisfy that regex will be identified as incomplete, and replaced with `cube:Undefined`
=> fix: cube:Undefined for broken references

.changeset/gentle-lions-impress.md, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/domain/shared-dimension/import.ts, apis/shared-dimensions/lib/domain/shared-dimension/importShapes.ttl, apis/shared-dimensions/lib/handlers/shared-dimension.ts, apis/shared-dimensions/lib/resource.ts, apis/shared-dimensions/lib/store.ts, apis/shared-dimensions/test/lib/domain/managed-dimension.test.ts, fuseki/shared-dimensions.trig
This finally improves the shared dimension export:
1. No longer export the generated shapes describing resource (only resource data). The shapes will be recalculated on import (see the extracted function `extractShape`)
2. The exported resources are loaded from store in the same way we do for `GET` requests, hence re-used the `resourceQueryPatterns` method
This PR is instrumental in completing #970 so that the dynamic properties will be properly exported but I did not want to mix up these changes
=> fix: shared dim export without shape

.changeset/quick-flowers-leave.md, apis/core/lib/domain/dataset/update.ts, apis/core/test/domain/dataset/update.test.ts, packages/core/namespace.ts
- Use `schema:contactPoint` instead of `lindas:contactPoint`
- Avoid storing a new `schema:contactPoint` every time the dataset is saved
=> Fix contactPoint

.changeset/red-zebras-boil.md, cli/lib/toCubeShape/Cube.js, cli/lib/toCubeShape/Dimension.js, cli/lib/toCubeShape/index.js, cli/test/lib/commands/transform.test.ts
This PR excludes dimension's `sh:in` constraint when the number of distinct values exceeds a configurable threshold. By default `100`
=> feat(cli): cut-off point for sh:in size

.changeset/neat-months-teach.md, apis/core/bootstrap/shapes/dimension.ts
The new description will be shown on the dimension metadata form
=> chore: inform about the "soft" dimension type sync

apis/core/bootstrap/shapes/dataset.ts
I noticed the issue while tested the new nested validation results. `sh:targetClass` would cause the nested shape to be applied twice: once because of `sh:node` and once because of `sh:targetClass`. The validation results would also appear twice: once at the root of the report because of `sh:targetClass`, and once nested because of `sh:node`.
=> Remove `sh:targetClass` from nested shape

.changeset/twenty-plums-grin.md, apis/core/lib/domain/csv-source/delete.ts, apis/core/lib/domain/csv-source/replace.ts, apis/core/lib/domain/csv-source/update.ts, apis/core/lib/domain/csv-source/upload.ts, apis/core/lib/domain/cube-projects/export.ts, apis/core/lib/handlers/csv-source.ts, apis/core/test/domain/cube-projects/export.test.ts, cli/lib/csv.ts, packages/model/CsvSource.ts
Prior to this PR we would export the S3 location to sources as they appeared in the original project. If said project would be imported to same environment, these files would be deleted to "make room" for new project's CSVs
This removes the actual paths to uploaded CSVs so they will not be inadvertently deleted
=> fix: "disappearing" CSVs

.changeset/calm-boxes-sort.md, ui/src/components/HydraOperationErrorResult.vue
Nested errors would not display because of the way recursive components
work in Vue. For some reason, this was not happening locally when
developping. I guess compilation stripes away component name.
=> fix: nested errors not displaying

.changeset/six-jobs-shout.md, apis/core/lib/Loader.ts
This greatly reduces the queries which discover potential links with hydra operations.
Since we've added activity log for resource changes, these have been constantly growing because every resource is linked to its log entries by `as:object` predicate. This PR simply excludes that link from being considered by hydra.
=> refactor: reduce hydra-box queries

.changeset/tender-crabs-call.md, apis/core/bootstrap/shapes/csv-source.ts, apis/core/lib/domain/csv-source/upload.ts, e2e-tests/csv-source/get-csv.hydra, e2e-tests/csv-source/update.hydra, e2e-tests/csv-source/upload.hydra, minio/cube-creator/test-data/get-test-cube/test.csv
The upload used to store "empty string" as delimiter and quote char when
they could not be determined from the file. Store `undefined` instead
and make these 2 fields optional.
=> fix: make all fields optional in CSV dialect form

.changeset/poor-llamas-allow.md, ui/src/forms/editors/IdentifierTemplateEditor.vue
The `keep-first` option would somehow find an option when no options are
actually valid, which resulted in a weird behavior when editing the
identifier.
=> fix: weird behavior in identifier template input

.changeset/heavy-walls-scream.md, apis/core/bootstrap/shapes/dimension.ts, packages/model/DimensionMetadata.ts, ui/src/store/modules/project.ts, ui/src/store/serializers.ts
- Add a `sh:order` property on dimension metadata (manually input in the form for now)
- Sort dimensions by
1. Order
2. Measure dimension
3. Key dimension
4. Alphabetically (property)
Part of #700, but only with the simplest UI possible: a field to enter the order value.
=> feat: add dimension order property

.github/workflows/docker-api.yaml, .github/workflows/docker-app.yaml, .github/workflows/docker-cli.yaml
I figure that we should only run the docker packaging on pull. Running also on PR hooks is a little pointless because the `branch` tags will be the same
=> ci: no need to build images on PR hook

.changeset/bright-bikes-talk.md, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/loader.ts, apis/shared-dimensions/lib/resource.ts, apis/shared-dimensions/lib/store.ts, apis/shared-dimensions/test/store.test.ts
Every resource in shared dimensions API is stored alongside a shape which describe its properties. See [the example data](https://github.com/zazuko/cube-creator/blob/8b6a59ab0c1713ccb0338beb8e78881b9048e442/fuseki/shared-dimensions.trig#L77-L102)
Until now to retrieve a resource from that API we ran a single query which used property paths to query those shapes and build patterns to get the precise triples. This same implementation was used to delete and update resources, and export a dimension
This proved quite ineffective on Stardog. I assume that SPARQL property paths are to blame. 
This PR changes the implementation so that any needed shape(s) are retrieved first with a fast `CONSTRUCT` and the SHACL properties are recessed in memory to avoid deep SPARQL Paths in `OPTIONAL` clauses. …
=> fix: leftover shapes in shared dimension DB and very slow queries

cli/lib/loadCube.ts
I found Fuseki having issues with this query. By running the path pattern first we greatly improve performance (to put mildly, because suddenly the query stopped working on my box)
Might also be beneficial on Stardog
=> perf: reorder query patterns

.changeset/strange-toys-serve.md, packages/model/Table.ts
Crashing may not be the wrong behavior, but it doesn't belong in the getter of `parsedTemplate`.
=> fix: do not crash when missing table identifier template

.changeset/cool-radios-tie.md, apis/core/lib/domain/queries/dimension-metadata.ts
The missing pattern joining the table to its mapping resource would produce an unwanted cross-product of columns from multiple projects.
In the case of #1097, there exists a `jahr` column in another project which is a key dimension, thus it was wrongly determined as such when setting the default value in the form
=> fix: missing join on project's mapping resource

.lando.yml, ui/vue.config.js
As of #1095 the web app running in lands container failed trying to access the insecure `ws://` websockets (cause by upgrade to webpack 5?).
I did not find a way to switch to `wss://` so this disables the sockets completely (and thus live reload)
=> build(ui): disable hot-reload in lando

.github/workflows/setup-env/action.yml, .lando.yml, fuseki/config.ttl
I wanted to check if running the application locally using `lando` on a M1 machine was working.
It was mostly the case, the only part that was broken is the store (Fuseki).
I replaced the image with the version we are maintaining ourselves, and it gives the following advantages:
- it's running on the following architectures: `amd64` and `arm64` instead of only `amd64`
- it's using the latest version of Apache Jena
- we can enable OpenTelemetry if we want
=> chore: use our own Fuseki image

.changeset/real-poets-play.md, cli/index.ts, cli/lib/commands/runner.ts, cli/package.json
Small improvement for running jobs from remote environments locally.
By skipping the job status update we will be able to run a job without confusing and potentially misleading changes of the jobs listed in the application
=> feat(cli): --no-status-update flag

.changeset/tall-pots-drop.md, apis/shared-dimensions/lib/domain/hierarchies.ts, packages/core/namespace.ts
A simple mistake which caused hierarchies from inside cubes to show up in the main listing. Instead of `meta:Hierarchy` we should use `md:Hierarchy` which is a more specific type used by the API itself
Similar to how we have `md:SharedDimension` as an API specific (informal) subclass of `schema:DefinedTermSet`
=> fix: correct type to find hierarchies

ui/src/store/serializers.ts, ui/src/use-polling.ts, ui/src/views/CubeProject.vue, ui/src/views/Job.vue, ui/src/views/Materialize.vue, ui/src/views/Publication.vue
With the new structure of the app, it is a waste to poll all jobs every
3 seconds on any page of the project.
With this change, jobs will only be polled on jobs listing pages. And
the detail page of a job will only poll the job itself, not the full
collection.
=> refactor: only poll jobs when necessary

.changeset/moody-mayflies-hug.md, apis/core/bootstrap/shapes/dimension.ts, apis/shared-dimensions/lib/domain/shared-dimensions.ts, package.json, ui/package.json, ui/src/forms/editors/AutoCompleteEditor.vue, yarn.lock
Adds an option to display hints in autocomplete editor. Here' used to add the shared dimension name next to terms in mapping screen
This is achieved by retrieving the necessary data from the endpoint which populates the dropdown and annotating the SHACL Property
```turtle
[]
a sh:PropettyShape ;
sh1:itemHelptextPath ( schema:inDefinedTermSet schema:name ) ;
.
```
The UI uses `sh1:itemHelptextPath` to find the labels to display as a second line in the dropdown
TODO:
=> feat: show hints when mapping shared dimension terms

ui/src/api/index.ts, ui/src/components/HydraOperationForm.vue, ui/src/components/HydraOperationFormWithRaw.vue, ui/src/components/JobForm.vue, ui/src/components/LiteralColumnMappingForm.vue, ui/src/store/modules/api.ts, ui/src/use-hydra-form.ts, ui/src/views/ColumnMappingCreate.vue, ui/src/views/ColumnMappingEdit.vue, ui/src/views/CubeMetadataEdit.vue, ui/src/views/CubeProjectCreate.vue, ui/src/views/CubeProjectEdit.vue, ui/src/views/DimensionEdit.vue, ui/src/views/DimensionMapping.vue, ui/src/views/HierarchyCreate.vue, ui/src/views/HierarchyEdit.vue, ui/src/views/SharedDimensionCreate.vue, ui/src/views/SharedDimensionEdit.vue, ui/src/views/SharedDimensionTermCreate.vue, ui/src/views/SharedDimensionTermEdit.vue, ui/src/views/SourceEdit.vue, ui/src/views/TableCreate.vue, ui/src/views/TableEdit.vue
All the views presenting a Hydra operation form consist of the same code with slight variations. This is a long overdue refactoring to extract the common parts.
=> Finally extract common code from forms

.changeset/giant-plants-invent.md, apis/shared-dimensions/lib/handlers/shared-dimensions.ts, apis/shared-dimensions/lib/middleware/canonicalRewrite.ts, apis/shared-dimensions/lib/shapes/hierarchy.ts
I added a query param which disables the rewrite from cube creator URIs to canonical URIs
Because the canonical URIs were not returned, the introspection query does not return anything when trying to find shared term properties
=> fix: use canonical dimension URIs in hierarchy form

.changeset/moody-rice-call.md, ui/src/forms/editors/HierarchyPathEditor.vue
By faking the selected property, we ensure that a new introspection query gets generated
Otherwise, it was impossible to properly toggle the checkbox without selecting a predicate
=> fix: "inverse" toggle

.changeset/happy-colts-mate.md, ui/src/views/Hierarchy.vue
Removed the root URIs from the hierarchy "Definition" since they are repeated anyway in the expandable tree just below
=> fix: remove hierarchy roots from page

.changeset/thin-frogs-explode.md, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/resource.ts, apis/shared-dimensions/package.json, yarn.lock
Reduces the size of `CONSTRUCT` by combing patterns of common subject. To prevent an excess of duplicate triples, which can bring down the database, the `WHERE` patterns are separated into a series of UNION to prevent a massive cartesian
=> fix: smaller CONSTRUCT

.changeset/breezy-fans-smash.md, ui/src/components/HydraOperationForm.vue
This effectively prevents due from observing changes in the shapes dataset, resulting in way fewer updates (which is some cases fall into an endless loop)
=> Reduce vue updates coming from SHACL Form

.changeset/grumpy-planes-enjoy.md, cli/lib/loadCube.ts, cli/lib/metadata.ts, cli/lib/project.ts, cli/test/lib/metadata.test.ts, fuseki/sample-ubd.trig
The query built to retrieve cube metadata was previously meant to exclude concepts which appear in `sh:in` lists
The filter used inadvertently also excluded triples deep inside `sh:or`, which resulted in dangling blank nodes without the expected `sh:datatype`
=> fix: publishing cube with sh:or

.changeset/yellow-peaches-pull.md, apis/shared-dimensions/lib/handlers/hierarchy.ts, apis/shared-dimensions/lib/middleware/canonicalRewrite.ts
Further tweaks to have hierarchy roots served in their canonical URI
Previously, in #1172, I added a change to have hierarchy roots loaded as `ld.admin.ch` in the editor form. This was not enough, because they would still be rewritten when loading the hierarchy itself (both when editing and showing the preview tree)
By expanding the semantics of `res.locals.noRewrite` there is more fine-grained control fo what gets rewritten. In this case we selectively exclude `meta:hierarchyRoot`
=> fix: do not rewrite hierarchy roots

.changeset/beige-schools-pump.md, .changeset/serious-rocks-lay.md, .changeset/tender-actors-warn.md, apis/core/bootstrap/shapes/dimension.ts, apis/core/bootstrap/shapes/index.ts, apis/core/hydra/dimension-mapping.ttl, apis/core/lib/ResourceStore.ts, apis/core/lib/domain/dimension-mapping/DimensionMapping.ts, apis/core/lib/domain/dimension-mapping/update.ts, apis/core/lib/domain/dimension/update.ts, apis/core/lib/domain/queries/dimension-mappings.ts, apis/core/lib/handlers/dimension-mapping.ts, apis/core/lib/middleware/resource.ts, apis/core/package.json, apis/core/test/domain/dimension-mapping/update.test.ts, apis/core/test/domain/queries/dimension-mappings.test.ts, e2e-tests/dimension-mapping/update.hydra, fuseki/sample-ubd.trig, fuseki/shared-dimensions.trig, packages/core/namespace.ts, packages/core/namespaces/shapes.ts, ui/src/api/index.ts, ui/src/forms/editors/DictionaryTableEditor.vue, ui/src/forms/editors/index.ts, ui/src/router.ts, ui/src/use-hydra-form.ts, ui/src/views/DimensionMapping.vue, ui/src/views/DimensionMappingImport.vue, yarn.lock
This brings a two changes:
1. In-browser paging of mapped terms
2. Import feature to populate the mappings from a Shared Dimension
**Live preview**
https://user-images.githubusercontent.com/588128/168161755-31677cef-8534-40b1-baef-6e29c1ea73e3.mp4
**Important notes**
Any new dimension mapped to a shared dimension will be automatically enabled for terms import.
Existing projects must be updated using a SPARQL update
<details>
<summary>
**🔍 Show query**
</summary>
```sparql
PREFIX prov: <http://www.w3.org/ns/prov#>
prefix cc: <https://cube-creator.zazuko.com/vocab#>
INSERT {
GRAPH ?mappingDictionary {
?mappingDictionary cc:batchMapping ?importTerms
}
}
where {
graph ?mappingDictionary {
?mappingDictionary a prov:Dictionary .
}
filter (
not exists {
graph ?mappingDictionary { …
```
=> Auto mapping shared dimensions

.changeset/great-dingos-dress.md, apis/shared-dimensions/lib/domain/shared-dimension.ts, apis/shared-dimensions/lib/resource.ts
We are still having issues with `413 Payload Too Large` when exporting dimensions with many terms
This is because currently the export happens in two queries. First one find all properties of shared terms from their persisted shapes. The second then does a massive CONSTRUCT with those exact patterns. It quickly grows out of proportion and it simply unnecessary. Here's a sample diff of how this PR changes the export to be executed in only one query
```diff
CONSTRUCT {
?s ?p ?o 
}
FROM <https://lindas.admin.ch/cube/dimension>
WHERE {   
{     
SELECT ?rootShape  WHERE {   
?term schema:inDefinedTermSet* <https://ld.admin.ch/cube/dimension/baqua> .   
?rootShape sh:targetNode ?term .    
MINUS {    
?propertyShape sh:node ?rootShape .  
}    
}   
}
- ?rootShape (!sh:targetNode)* ?s .
+ …
```
=> fix: no enormous CONSTRUCT

.changeset/curvy-lamps-lick.md, .changeset/nine-tomatoes-own.md, apis/core/lib/domain/column-mapping/delete.ts, apis/core/lib/domain/cube-projects/delete.ts, apis/core/lib/handlers/cube-projects.ts, apis/core/test/domain/column-mapping/delete.test.ts, apis/core/test/domain/cube-projects/delete.test.ts, fuseki/sample-ubd.trig, ui/tests/e2e/specs/project-mapping.spec.ts
I found two cases when deleting resources would leave some dangling leftovers
1. When removing a column mapping, the dimension mapping would not be removed
2. When deleting the entire project, a lot was not removed
In the latter case I opted for simply dropping all graphs which share the project's URL stem (all resources are named as `https://{Project URL}/{child resource path}`
=> Project delete

.changeset/shaggy-pants-hunt.md, .changeset/spotty-panthers-train.md, apis/shared-dimensions/hydra/index.ttl, apis/shared-dimensions/index.ts, apis/shared-dimensions/lib/middleware/canonicalRewrite.ts, apis/shared-dimensions/package.json, yarn.lock
hydra-box by default create the ApiDocumentation term using request context. Because we use `camouflage-rewrite`, that would have been a bogus `https://ld.admin.ch/dimension/api`. 
This would have caused issues when the front end failed to find the right hypermedia descriptions to generate forms
=> fix: shared dimension API Documentation resource

.changeset/big-jars-sneeze.md, cli/lib/commands/timeoutJobs.ts
While investigating #1218 I found that there are still numerous jobs "blinking"
That was because the query checked only for `dcterms:modified` which is set one job starts and the status gets updated. A new job, which never got the first update would not match.
=> fix: job timeout ignored jobs without `dcterms:modified`

.changeset/hip-tools-work.md, .github/workflows/test-pipelines.yaml, cli/lib/commands/timeoutJobs.ts, cli/lib/job.ts, cli/lib/log.ts, cli/test/lib/commands/timeoutJobs.test.ts, fuseki/sample-ubd.trig, package.json, packages/core/namespace.ts, ui/src/components/JobStatus.vue
To properly fix #1218, I figure I would need a separate "canceled" status for jobs neither failed, nor succeeded.
Might as well assign that status to timeout jobs. Especially that I noticed that some "blinking" jobs were actually successful but somehow the update did not register...
=> feat: separate status and icon for canceled jobs

.changeset/flat-gifts-relate.md, apis/core/lib/Loader.ts, apis/core/package.json, package.json, yarn.lock
I finally figured out one problem with API performance
There was unchecked query which should only run a basic pattern with `FROM` clauses.
```sparql
SELECT ?parent ?type
FROM <link-1> 
FROM <link-2>
WHERE {
graph ?parent {
?parent a ?type
}
}
```
However, that should only be executed when there are links to look up. The problem was that in such cases, the query would have been completely unbound (no `FROM`) resulting in huge results.
Additionally, I also improved th query before that, which actually finds these linked resources
=> fix: API performance of common requests

.changeset/empty-shoes-smile.md, apis/core/package.json, yarn.lock
TL;DR; a query was generated to load projects' mapping resources in a single request. That request used many `FROM` claueses
```sparql
CONSTRUCT { ?s ?p ?o }
FROM <A>
FROM <B>
FROM <C>
FROM <D>
WHERE { ?s ?p ?o }
```
This proved to be slow as the number of graphs grow. On the other hand this is fast
```sparql
CONSTRUCT { ?s ?p ?o }
WHERE {
{ GRAPH <A> { ?s ?p ?o } }
UNION
{ GRAPH <B> { ?s ?p ?o } }
UNION
{ GRAPH <C> { ?s ?p ?o } }
UNION
{ GRAPH <D> { ?s ?p ?o } }
}
=> fix: performance of cube-projects resource

.changeset/four-jokes-sin.md, apis/core/lib/domain/errors/duplicateObservations.ts, apis/core/lib/domain/errors/missingDimensions.ts
**Background**
In cube creator, we attach a `schema:error` to cubes when problems are identified with the data, etc. They should be removed after transformation when these problems no longer occur.
**Problem**
The 2 warnings in the issue report were not properly removed because the query in the form `DELETE/INSERT/WHERE` prevented that from happening. The `WHERE` clause did not match the issue condition and thus the `DELETE` was not performed.
**Solution**
Instead of a single update, I separated them to make two
```sparql
DELETE {} WHERE {}
INSERT {} WHERE {}
```
This way, the delete is always done and if the `INSERT` find nothing, then an existing error is gone for good. It also made it possible to remove an `OPTIONAL`, now unnecessary
=> fix: errors should be cleared

.changeset/large-phones-grow.md, apis/core/lib/domain/errors/deleteCurrent.ts, apis/core/lib/domain/errors/duplicateObservations.ts, apis/core/lib/domain/errors/missingDimensions.ts, apis/core/package.json, cli/test/lib/commands/transform.test.ts, fuseki/sample-ubd.trig, packages/model/Dataset.ts, yarn.lock
I noticed one more small issue, that instead of removing an error completely when it no longer applies to a given cube, empty yellow rows remain in the cube designer.
That is because the SPARQL removed the error details but not the error node itself. 
```turtle
<dataset>
schema:error <dataset#error-id> .
<dataset#error-id>
schema:description "Displayed on UI" .
```
This PR makes sure that the errors are properly cleaned
=> fix: no blank cube warnings

.changeset/twenty-carrots-behave.md, apis/core/lib/domain/job/create.ts
Related: https://gitlab.ldbar.ch/vshn/gitops-main/-/merge_requests/86
=> fix: visualize link dataset as query string

.changeset/seven-islands-battle.md, apis/core/bootstrap/organizations.ts
Voilà. 
As the link https://register.ld.admin.ch/opendataswiss/org/agroscope showed something, I used that one instead of the staatskalender...
=> feat: add agroscope as publisher

.changeset/gorgeous-pens-deliver.md, apis/core/lib/domain/queries/dimension-mappings.ts, apis/core/package.json, apis/core/test/domain/queries/dimension-mappings.test.ts
This changes how new dimension mappings are saved to the database when "auto-mapping"
The current implementation performed an `INSERT` with a complex pattern and a long list `VALUES` clause. Potentially thousands of items long.
Since the full set of these `VALUES` is loaded to memory anyway, they are actually cross-referenced in memory and new items are streamed directly as quads using the graph protocol. This appears much more database-friendly. While Stardog does cope, local fuseki actually failed to insert when mapping a large dimension of municipalities (3k terms)
=> refactor: graph store post new dimension mappings

.changeset/tiny-carrots-chew.md, apis/core/lib/domain/dimension-mapping/DimensionMapping.ts, apis/core/test/domain/dimension-mapping/update.test.ts
Dimension mappings are stored as instances of `prov:KeyEntityPair` similar to 
```turtle
[
rdf:type prov:KeyEntityPair ;
prov:pairKey "164" ;
prov:pairEntity <https://ld.admin.ch/dimension/term> ;
] .
<https://ld.admin.ch/dimension/term> a prov:Entity .
```
When such a pair was removed, the `a prov:Entity` triple was left over. It does not have any side effects but is clutter nonetheless. This PR ensures that they will be removed when a dimension mapping is saved.
Additioanally the query below can be used to clean up any dangling triples from mapping graphs.
```sparql
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX cube: <https://cube.link/>
DELETE {
graph ?mapping {
?entity a prov:Entity .
}
}
where {
graph ?mapping {
?mapping a prov:Dictionary …
```
=> fix: clean up dimension mapping graphs

.lando.yml
Using `node:custom` and specifying the image version in `overrides` allows the local set up to work on macOS Catalina which is not supported by later versions of lando (last being 3.6.5)
=> build(lando): node:custom

.changeset/six-phones-matter.md, ui/src/customElements/HydraRawRdfForm.ts
During previous refactoring the event handler was attached wrong and submit never happened from the element `cc-hydra-raw-rdf-form`
=> fix: submitting raw rdf form

.changeset/fuzzy-moose-compare.md, apis/core/lib/domain/dimension-mapping/DimensionMapping.ts, apis/core/lib/domain/dimension-mapping/update.ts, apis/core/package.json, apis/core/test/domain/dimension-mapping/DimensionMappings.test.ts, apis/core/test/domain/dimension-mapping/update.test.ts, yarn.lock
Using the strongly-types interface for manipulating (large) dimension mappings was quite memory-intensive to the point where pods were being restarted
This changes this process to use clownface directly
=> fix: use only clownface for mappings to reduce memory

.changeset/funny-chairs-press.md, apis/core/bootstrap/shapes/dimension.ts
The query for units needs to be expanded to find both `qudt:Unit` and `qudt:CurrencyUnit`
=> fix: missing currencies

apis/core/package.json, cli/lib/loadCube.ts, cli/pipelines/publish.ttl, yarn.lock
I found that the publish job had issues when it tried to update the status in case of cube validation failure. Turned out that the cause was invalid SPARQL where the cube-link validation shapes were serialized as invalid prefixed names like `cube:shape/standalone-constraint-constraint#PropertyWithName`, lacking the escaping of slash and hash.
While I was on it, I simplified the `loadCube.ts`. Can't remember anymore why there was that `PassThrough`. It appears redundant now
=> Fix publish job using newest barnard59

.changeset/unlucky-lobsters-jam.md, apis/core/bootstrap/shapes/column-mapping.ts, apis/core/lib/domain/column-mapping/ColumnMapping.ts, apis/core/lib/domain/column-mapping/create.ts, apis/core/test/domain/column-mapping/create.test.ts, cli/lib/validation.ts, e2e-tests/column-mapping/create.hydra, e2e-tests/column-mapping/update-literal.hydra
Use a SHACL shape to prevent mixing language and datatype (`xsd:string` is treated as an exception and silently replaced with `rdf:langString` to avoid bothering the user with this subtle distinction).
Provide detailed but simple error messages for invalid values of the supported data types (with links to formal specs).
=> Error messages

.changeset/loud-news-drop.md, .github/workflows/ci.yaml, README.md, cli/README.md, cli/lib/commands/transform.ts, cli/lib/job.ts, cli/lib/metadata.ts, cli/lib/variables.ts, cli/pipelines/main.ttl, cli/pipelines/publish.ttl, cli/test/lib/commands/publish.test.ts, cli/test/lib/commands/transform.test.ts, fuseki/sample-ubd.trig, package.json, packages/model/Job.ts
builds upon #1508 . The `cube:observedBy` property is set with the correct value during the _transform_  job, avoiding the need to replace the values during the _publish_ job. We gain in simplicity: the correct value, derived from the publishing profile in the project settings, is passed as ENV variable, it's used for all observations and the corresponding cube constraint is automatically derived. The only downsize I see is the need to rerun the _transform_  job if one changes the publishing profile.
=> Fix observer

cli/lib/metadata.ts, cli/pipelines/main.ttl, cli/pipelines/publish.ttl, cli/test/lib/commands/publish.test.ts, cli/test/lib/commands/transform.test.ts
- pass contributor as argument
- make `cube:observedBy` to be consistent in the ObservationConstraint
- add test
- drop injection
=> improve validation: ensure consistent observedBy in ObservationConstraint

.changeset/selfish-hotels-exist.md, cli.Dockerfile
let's discuss here also with @ludovicm67  if we want a more pervasive replacement of ADD with COPY
=> copy all turtle files in the docker image

.changeset/rude-toes-design.md, .github/workflows/setup-env/action.yml, apis/shared-dimensions/bootstrap/hierarchies.ts, apis/shared-dimensions/bootstrap/index.ts, apis/shared-dimensions/hydra/index.ttl, apis/shared-dimensions/lib/domain/hierarchies.ts, apis/shared-dimensions/lib/handlers/hierarchy.ts, apis/shared-dimensions/lib/store/shapes.ttl, e2e-tests/hierarchies/external-hierarchy.hydra, fuseki/hierarchies.trig, fuseki/shared-dimensions.trig, packages/core/namespace.ts, ui/src/api/common.ts, ui/src/forms/plugins/dimensionMetaHierarchySynchronizer.ts, ui/src/store/modules/hierarchy.ts
I added a "proxy" endpoint where Cube Creator can fetch hierarchies from Lindas. This way they can be displayed and used in the Cube Designer
=> Hierarchies from all graphs
