.gitignore
.lando.yml
.local.env
apis/core/frontend.ts
apis/core/index.ts
apis/core/lib/env.ts
package.json
ui/package.json
ui/public/index.html
ui/src/App.vue
ui/src/components/NavBar.vue
ui/src/components/auth/OidcCallback.vue
ui/src/components/auth/OidcError.vue
ui/src/components/auth/SignOutButton.vue
ui/src/main.ts
ui/src/router/index.ts
ui/src/store/index.ts
ui/src/store/modules/auth.ts
ui/src/views/Home.vue
ui/tsconfig.json
ui/types/global.d.ts
yarn.lock

We still have an issue causing the UI to continuously call the OIDC provider for a while for some reason. This issue is also present in the original data-cube-curation tool.

feat(ui): authentication using OIDC

---

ui/.eslintrc.json
ui/src/App.vue
ui/src/components/NavBar.vue
ui/src/components/auth/SignOutButton.vue

Not a big change but it should make upcoming code a bit more consistent

style(ui): enforce slightly stricter rules

---

README.md

I added a section workflow into the read-me.
A question still around from my side was if there is a need for a standard naming conventions for branches.

add workflow to read-me

---

apis/readme.md

Some notes on the back end project structure etc

APIs readme

---

apis/core/index.ts
apis/core/lib/env.ts
apis/core/package.json
yarn.lock

fixes #35
As requested, I added optional variables `STORE_ENDPOINTS_USERNAME` and `STORE_ENDPOINTS_PASSWORD` to provide endpoint credentials

feat(api): configuring SPARQL credentials with env variables

---

apis/core/lib/auth.ts
apis/core/lib/domain/cube-projects/create.ts
apis/core/lib/domain/identifiers.ts
apis/core/lib/handlers/cube-projects.ts
apis/core/test/domain/cube-projects/create.test.ts
e2e-tests/cube-projects/create.hydra

Add the creation user to a newly created cube project
Closing #41

feat: store user info when creating project

---

packages/core/namespace.ts
ui/package.json
ui/src/api/common.ts
ui/src/api/index.ts
ui/src/api/mixins/ProjectsCollection.ts
ui/src/components/SidePane.vue
ui/src/router/index.ts
ui/src/store/modules/cube-projects.ts
ui/src/types.ts
ui/src/views/CubeProjectNew.vue
ui/src/views/CubeProjects.vue
ui/src/views/PageNotFound.vue
yarn.lock

There are still a lot of things to be figured out, but it already allows to create a cube project.

feat(ui): create cube project

---

ui/src/router/index.ts

We don't have a homepage yet. Auto-redirect to the projects list.

feat: redirect home to cube-projects

---

ui/src/components/auth/SignOutButton.vue
ui/src/router/index.ts
ui/src/store/modules/auth.ts
ui/src/views/Logout.vue

feat: add post-logout page

---

ui/package.json
ui/src/App.vue
ui/src/api/index.ts
ui/src/api/mixins/Project.ts
ui/src/components/NavBar.vue
ui/src/components/PageContent.vue
ui/src/router/index.ts
ui/src/store/modules/cube-projects.ts
ui/src/types.ts
ui/src/views/CSVMapping.vue
ui/src/views/CubeDesigner.vue
ui/src/views/CubeProject.vue
ui/src/views/CubeProjects.vue
yarn.lock

Initial project page with tabs to mapper and designer

feat: add project page

---

ui/package.json
ui/src/bulma.scss
ui/src/main.ts
yarn.lock

Set a smaller font-size globally to avoid having to set it in every
component.

chore: customize bulma to adapt font size overall

---

.editorconfig
.lando.yml
README.md
apis/core/lib/domain/csv-source/upload.ts
apis/core/lib/domain/identifiers.ts
e2e-tests/csv-source/get-csv.hydra
e2e-tests/csv-source/upload.hydra

CSV: store dialect options and link to source

---

.local.env
apis/core/index.ts
apis/core/lib/errors/auth.ts
apis/core/lib/errors/index.ts
apis/core/package.json
yarn.lock

Any 401 and 403 errors will now include the Access Request link configured by env variable

feat: add access request link to error response

---

apis/core/lib/domain/csv-source/upload.ts
apis/core/lib/domain/identifiers.ts
e2e-tests/csv-source/upload.hydra
packages/core/namespace.ts

Read columns from CSV File and some sample data and save them to the graph attached to the correspending csv-source
fix #62

feat: Extract columns

---

ui/src/api/index.ts
ui/src/api/mixins/CSVColumn.ts
ui/src/api/mixins/CSVSource.ts
ui/src/components/CsvSourceMapping.vue
ui/src/types.ts

feat(ui): display CSV columns with sample values

---

apis/core/lib/domain/csv-source/upload.ts
apis/core/lib/domain/csv/sample-values.ts

Fixing https://github.com/zazuko/cube-creator/pull/70#discussion_r507517264 .
Since the frontend code seems to only care about 3 unique values per row that's what I went for as well but there's a param to tweak it.

Extract unique values per column

---

apis/core/hydra/csv-source.ttl
packages/core/namespace.ts
ui/src/App.vue
ui/src/api/mixins/CSVSource.ts
ui/src/components/CsvSourceMapping.vue
ui/src/store/index.ts
ui/src/store/modules/api.ts
ui/src/store/modules/app.ts
ui/src/store/modules/cube-projects.ts
ui/src/store/types.ts
ui/src/types.ts

Display potential CSV parsing error.
I also added a way to delete the source, but I had no idea how to implement the API handler so I left it missing.

feat: display CSV parsing error

---

apis/core/hydra/table.ttl
apis/core/lib/domain/identifiers.ts
apis/core/lib/domain/table/create.ts
apis/core/lib/handlers/table/create.ts
apis/core/test/domain/table/create.test.ts
e2e-tests/table/create.hydra

Endpoint to create a table

---

ui/src/forms/index.ts
ui/src/views/CubeProjectNew.vue

By default, shaperone wraps a focus node fieldset in a `<form>` tag, which makes it impossible to control the behavior of the form. I just replaced the default renderer with a custom one without the form tag.

Fix weird form behavior

---

apis/core/bootstrap/shapes/table.ts
apis/core/hydra/table.ttl
apis/core/lib/domain/identifiers.ts
apis/core/lib/domain/table/create.ts
apis/core/package.json
packages/core/namespace.ts
ui/src/api/index.ts
ui/src/api/mixins/ColumnMapping.ts
ui/src/api/mixins/Table.ts
ui/src/bulma.scss
ui/src/components/CsvSourceMapping.vue
ui/src/components/HydraOperationButton.vue
ui/src/components/MapperTable.vue
ui/src/forms/BulmaCheckbox.vue
ui/src/forms/FormProperty.vue
ui/src/forms/components.ts
ui/src/forms/matchers.ts
ui/src/views/CSVMapping.vue
ui/src/views/TableCreate.vue
yarn.lock

Create default column mappings for table

---

apis/core/lib/domain/csv-source/upload.ts
apis/core/lib/domain/csv/file-head.ts
apis/core/lib/handlers/csv-source.ts
apis/core/lib/storage/s3.ts

I discovered that we did not upload the entire file and @tpluscode observed some performance problems. this PR fixes both

Fix: file upload

---

apis/core/lib/domain/cube-projects/Project.ts
apis/core/lib/domain/cube-projects/create.ts
apis/core/lib/domain/identifiers.ts
apis/core/test/domain/cube-projects/create.test.ts

Creates the default mapping namespace as resource `${BASE_URI}/cube/${project-slug}`

fix: assume default cc:namespace

---

apis/core/hydra/table.ttl
apis/core/lib/domain/csv-mapping/delete.ts
apis/core/lib/domain/csv-source/delete.ts
apis/core/lib/domain/queries/table.ts
apis/core/lib/domain/table/delete.ts
apis/core/lib/handlers/table/delete.ts

Adds an API point to delete a table
Tables will deleted, when a project is deleted
fix #121

feat: delete table

---

apis/core/lib/domain/csv/file-head.ts

Some problem with line endings
Increased chunk size since it only read around 4 lines with an example file

fix: problem with end of line characters

---

ui/src/forms/URIInput.vue
ui/src/forms/components.ts
yarn.lock

Bare bones URI input. It does nothing special apart from creating a named node from a text input.

feat(ui): add URI input

---

ui/src/store/modules/auth.ts

fix(ui): enable auto silent token refresh

---

.github/workflows/ci.yaml
.gitignore
package.json
yarn.lock

Adding code coverage to mocha tests
I would not propose to enforce any specific coverage threshold but having a visual overview of covered code will help to assess which areas need more tests when adding new feature or fixing bugs

test: add code coverage and codecov

---

apis/core/lib/domain/csv-mapping/delete.ts
apis/core/lib/domain/csv-source/delete.ts
apis/core/lib/domain/queries/table.ts
apis/core/test/domain/csv-source/delete.test.ts
packages/model/Table.ts
ui/src/components/CsvSourceMapping.vue
ui/src/types.ts

Removes the link to the csvSource from the table when the source is deleted.
I did a refactoring to make the code testable and wrote a test
fixes #97

feat: remove source link from table when deleting

---

apis/core/bootstrap/shapes/table.ts
e2e-tests/table/create.hydra

Forces a identifier template since we do not have logic for auto generation.
Changed e2e test for table create such that it actually does something.

fix: force identifier template

---

packages/testing/lib/index.ts

fix: silent drops are required by stardog

---

ui/src/api/errors.ts
ui/src/components/HydraOperationForm.vue
ui/src/components/JobForm.vue
ui/src/views/ColumnMappingCreate.vue
ui/src/views/CubeProjectNew.vue
ui/src/views/SourceEdit.vue
ui/src/views/TableCreate.vue

This is still not very user friendly, but at least it will show some details about the error that happened when submitting the form.

feat(ui): improve form error messages

---

ui/package.json
ui/src/forms/BulmaCheckbox.vue
ui/src/forms/BulmaRadioButtons.vue
ui/src/forms/components.ts
yarn.lock

Bringing in a host of improvements to the form
1. Click ➕ multiple times and handle those fields independently
* **CAUTION** field `object` now an be undefined, when in a "no value state"
2. Update how elements are lazy-loaded
3. Fix checkbox (`update` must be called with an RDF/JS literal)
4. Nested `cc-form` should just work, honouring the shapes graph pointer
5. Nested blank nodes generated by `sh:minCount` are correctly connected the parent focus node

fix: form updates

---

apis/core/lib/csvw-builder/index.ts
apis/core/test/csvw-builder/index.test.ts

feat: populate csvw:datatype from column mapping

---

apis/core/lib/ResourceStore.ts
apis/core/lib/domain/cube-projects/create.ts
apis/core/test/domain/cube-projects/create.test.ts
fuseki/sample-ubd.trig
packages/core/namespace.ts
packages/model/Dataset.ts
packages/model/DimensionMetadata.ts
packages/model/lib/initializer.ts

Slightly reconsidered, fixes #185 
The dimension metadata collection gets attached to the dataset, its graph initialised

Metadata graph

---

apis/core/bootstrap/shapes/cube-project.ts
ui/src/styles/bulma.scss

Help text for mapping namespace

---

apis/core/bootstrap/shapes/table.ts
apis/core/hydra/table.ttl
packages/core/namespaces/shapes.ts
ui/src/components/MapperTable.vue
ui/src/router/index.ts
ui/src/views/TableEdit.vue

The operations don't edit in the API yet, but they should work right away in the UI once we add them.

Handle "delete column mapping" and "edit table" operations

---

apis/core/hydra/dataset.ttl
apis/core/lib/domain/queries/cube.ts
apis/core/lib/handlers/dataset.ts
e2e-tests/dataset/get.hydra
fuseki/sample-ubd.trig

extend the Dataset resource with cube shape and dimensions metadata

---

ui/src/forms/FormObject.vue
ui/src/forms/FormProperty.vue

This should allow clicking the label to select the related field.

fix(ui): bind form labels to input fields

---

ui/src/api/index.ts

I applied the same hack that we did in the first project. @tpluscode let me know if there's a better way.

fix(ui): memoize API documentation

---

apis/core/bootstrap/shapes/jobs.ts
apis/core/lib/middleware/shacl.ts

The SHACL validation did not target the right node and that failed validation

GitHub trigger

---

apis/core/lib/domain/column-mapping/create.ts
apis/core/lib/domain/column-mapping/lib/index.ts
apis/core/lib/errors/domain.ts
apis/core/lib/errors/index.ts
apis/core/test/domain/column-mapping/create.test.ts
e2e-tests/column-mapping/create.hydra

feat: prevent same property mapped twice

---

apis/core/bootstrap/shapes/column-mapping.ts
apis/core/lib/domain/table/Table.ts
apis/core/package.json
apis/core/test/domain/table/create.test.ts
e2e-tests/column-mapping/create-invalid.hydra
e2e-tests/table/create.hydra
fuseki/sample-ubd.trig
yarn.lock

fix: only allow certain characters in target property

---

ui/src/forms/index.ts

fix(ui): reactivity issue in forms

---

apis/core/bootstrap/shapes/dimension.ts
apis/core/test/domain/dimension/update.test.ts
e2e-tests/dimension-metadata/update.hydra
ui/src/forms/TextFieldWithLangEditor.vue
ui/src/forms/components.ts

feat: add dimension metadata description

---

apis/core/hydra/column-mapping.ttl
apis/core/lib/domain/column-mapping/update.ts
apis/core/lib/handlers/column-mapping.ts
apis/core/test/domain/column-mapping/update.test.ts
e2e-tests/column-mapping/update.hydra
fuseki/sample-ubd.trig
packages/model/ColumnMapping.ts
ui/src/views/ColumnMappingEdit.vue

Update a column mapping
fix #118

feat: update column mapping

---

apis/core/hydra/column-mapping.ttl
apis/core/lib/domain/column-mapping/update.ts
apis/core/lib/domain/dimension/DimensionMetadataCollection.ts
apis/core/lib/domain/queries/table.ts
apis/core/lib/handlers/column-mapping.ts
apis/core/test/domain/column-mapping/update.test.ts
apis/core/test/domain/csv-source/delete.test.ts
e2e-tests/column-mapping/update.hydra
fuseki/sample-ubd.trig
packages/model/ColumnMapping.ts
ui/src/views/ColumnMappingEdit.vue

Common base to start implementing #118 and #117

feat: apis column mapping

---

packages/core/namespace.ts
packages/core/package.json
packages/model/ColumnMapping.ts
packages/model/Project.ts
packages/model/Table.ts
yarn.lock

build(deps): update types for namespace builder

---

packages/model/Cube.ts
ui/src/api/index.ts
ui/src/components/CubePreview.vue
ui/src/components/TermDisplay.vue
ui/src/remote.ts

Display cube observations

---

apis/core/lib/domain/column-mapping/create.ts
apis/core/test/domain/column-mapping/create.test.ts

fix: only prevent same target property on observation tables

---

apis/core/lib/domain/table/update.ts

refactor: use delete of MetadataDimensionCollection

---

apis/core/lib/pipeline/trigger.ts
apis/core/test/pipeline/trigger.test.ts
packages/core/env.ts

feat: gitlab trigger

---

apis/core/lib/domain/table/Table.ts
packages/model/Table.ts
ui/src/api/mixins/Table.ts
ui/src/store/modules/project.ts
ui/src/store/serializers.ts

This is not a great solution, but it does fix most of the performance issues in the UI. There are probably ways to automate some of this.
Will fix #171

Improve UI performance by serializing rdfine objects

---

apis/core/lib/middleware/operations.ts
apis/core/package.json
yarn.lock

I have no idea why the csv resources return `405` on TEST. I totally failed to reproduce locally, running from the docker hub image and with a resource copied from Lindas
For now I've added some logging in the middlewares which filter out operations to see which one is to blame

chore: add logs of filtered operations

---

apis/core/lib/domain/column-mapping/update.ts
apis/core/test/domain/column-mapping/create.test.ts
apis/core/test/domain/column-mapping/update.test.ts

Fix duplicate target property column mapping check on update

fix: dup. column mapping property check on update

---

.github/workflows/pipeline.yaml
apis/core/hydra/job.ttl
apis/core/lib/domain/job/create.ts
apis/core/lib/handlers/jobs.ts
apis/core/lib/middleware/resource.ts
apis/core/lib/pipeline/trigger.ts
apis/core/test/domain/job/create.test.ts
apis/core/test/pipeline/trigger.test.ts
cli/lib/job.ts
cli/server.ts
e2e-tests/jobs.hydra
packages/core/namespace.ts
packages/model/Job.ts
ui/src/components/JobForm.vue

Feat/api publish cube WIP

---

ui/src/components/CsvSourceMapping.vue

fix(ui): message when no tables are mapped

---

packages/model/CsvSource.ts
ui/src/api/mixins/CSVSource.ts
ui/src/store/serializers.ts

fix(ui): display CSV source error

---

apis/core/bootstrap/shapes/cube-project.ts
apis/core/hydra/projects.ttl
apis/core/lib/domain/cube-projects/Project.ts
apis/core/lib/domain/cube-projects/update.ts
apis/core/lib/handlers/cube-projects.ts
apis/core/test/domain/cube-projects/update.test.ts
packages/core/namespaces/shapes.ts
ui/src/api/index.ts

Edit project API endpoint

---

apis/core/lib/domain/identifiers.ts
apis/core/test/domain/cube-projects/create.test.ts
cli/lib/cube.ts
cli/test/lib/cube.test.ts

Also improves appending the version to published cube (somewhat caused by the namespace issue)
fixes #272

Default Cube ID did not end in slash

---

.lando.yml

fix: fix minio version

---

apis/core/lib/csvw-builder/index.ts
apis/core/test/csvw-builder/index.test.ts

CsvColumn is not a resource...
Fixes #311

fix: identifier mapping column replacement

---

ui/src/components/HydraOperationForm.vue
ui/src/components/ReferenceColumnMappingForm.vue

chore: move validation error at bottom of forms

---

apis/core/bootstrap/shapes/cube-project.ts
ui/tests/e2e/specs/project-mapping.spec.ts

..and hide it from the project creation form
fixes #317

chore: add a default value for publish graph

---

apis/core/bootstrap/shapes/cube-project.ts
apis/core/lib/domain/cube-projects/update.ts
apis/core/test/domain/cube-projects/update.test.ts
ui/src/views/CubeProjectEdit.vue

Edit project namespace inline instead of in a nested form.
It should fix #313 and #329

feat: edit project namespace inline

---

apis/core/bootstrap/shapes/column-mapping.ts
ui/tests/e2e/specs/project-mapping.spec.ts

Addresses #340 
@tpluscode Is it correct to set the default datatype to `xsd:string` or will it cause issues that I didn't think about? (maybe with the language)

Add more datatypes

---

ui/src/store/serializers.ts
ui/src/views/Pipeline.vue

- Do not load csvMapping (not needed on this page)
- Serialize jobs (makes it easier on Vue's reactivity mechanism)
Fixes #347

Improve performance of jobs page

---

ui/src/components/CubePreview.vue

fix(ui): make large cube preview scrollable

---

apis/core/bootstrap/shapes/dataset.ts

fix: use schema.workExample to indicate where to publish

---

apis/core/lib/domain/column-mapping/delete.ts
apis/core/lib/domain/dimension/DimensionMetadataCollection.ts
apis/core/lib/domain/queries/column-mapping.ts
apis/core/lib/domain/table/delete.ts
apis/core/lib/domain/table/update.ts
apis/core/test/domain/column-mapping/create.test.ts
apis/core/test/domain/column-mapping/delete.test.ts
apis/core/test/domain/table/delete.test.ts
apis/core/test/domain/table/update.test.ts
yarn.lock

Deletes related dimensions when a table is deleted
fix #257

fix: delete dimensions when deleting table

---

apis/core/lib/domain/observations/index.ts
apis/core/lib/domain/observations/lib/index.ts
apis/core/test/domain/observations/index.test.ts
apis/core/test/domain/observations/lib/index.test.ts
typings/rdf-cube-view-query/index.d.ts
yarn.lock

Apply page size to observations query (right now still only first page)

feat: add real paging to cube view query

---

ui/src/components/MapperTable.vue
ui/src/store/serializers.ts

Display datatype and language in mapper table.
Fixes #333

feat(ui): display table column datatype/language

---

ui/src/components/CubePreview.vue
ui/src/store/modules/project.ts
ui/src/store/serializers.ts

Improve performance and fix an issue with rdfine not providing the dataset `title` (probably a clash between mixins again)

Serialize cube metadata

---

apis/core/lib/domain/observations/index.ts
apis/core/lib/domain/queries/observations.ts
apis/core/test/domain/observations/index.test.ts
ui/src/components/CubePreview.vue
ui/src/components/CubePreviewValue.vue
ui/src/router/index.ts
ui/src/views/ResourcePreview.vue

Show resource labels in cube preview

---

ui/src/api/errors.ts
ui/src/views/CSVUpload.vue

feat(ui): display custom error when uploaded file is too large

---

cli/lib/commands/publish.ts
cli/lib/cube.ts
cli/lib/loadCube.ts
cli/test/lib/cube.test.ts

Adding a little more logging to publish pipeline

fix: more log in publish pipeline

---

apis/core/lib/domain/csv-source/delete.ts
apis/core/test/domain/csv-source/delete.test.ts

@martinmaillard @lucafurrer do you remember why we only unset the table property and not actually remove the table?
fixes #309

fix: delete table when source removed

---

ui/src/components/CubePreview.vue
ui/src/components/CubePreviewValue.vue
ui/src/components/TermDisplay.vue
ui/src/rdf-properties.ts
ui/src/views/ResourcePreview.vue

Display shrunk version of custom URIs in Cube Preview.

feat(ui): shrink custom URIs in cube preview

---

apis/core/hydra/dataset.ttl
apis/core/lib/domain/observations/index.ts
apis/core/lib/domain/observations/lib/index.ts
apis/core/lib/handlers/dataset.ts
apis/core/lib/handlers/observations.ts
apis/core/test/domain/observations/index.test.ts
apis/core/test/domain/observations/lib/index.test.ts
e2e-tests/cube-observations/query.hydra
fuseki/sample-ubd.trig
ui/src/components/CubePreview.vue
ui/src/styles/app.scss
ui/src/styles/utilities.scss

Will fix #382 
It is functional, ~~but I have still a e2e test that fails locally. I need to investigate why.~~

Cube preview pagination

---

apis/core/lib/domain/observations/index.ts
apis/core/lib/domain/observations/lib/index.ts
apis/core/test/domain/observations/lib/index.test.ts

Precalculate page links

---

ui/package.json
ui/src/forms/FormProperty.vue
ui/tsconfig.json
ui/types/vue-markdown.d.ts
yarn.lock

feat(ui): render form help as markdown

---

ui/src/components/PropertyDisplay.vue
ui/src/forms/editors/PropertyInput.vue
ui/src/store/modules/project.ts
ui/src/views/DimensionEdit.vue

fix(ui): broken property full-URI hover

---

fuseki/sample-ubd.trig

Proposed API resources to hold dimension mappings
The CI will fail, to be fixed in subsequent PRs

chore: managed dimension sample

---

ui/src/components/CsvSourceMapping.vue
ui/src/components/MapperTable.vue
ui/src/views/CSVMapping.vue

Display lines between source and table on hover

---

cli/lib/metadata.ts
cli/test/lib/commands/publish.test.ts

feat: publish links to parent cube

---

apis/core/bootstrap/lib/query.ts
apis/core/bootstrap/shapes/dimension.ts
ui/package.json
ui/src/forms/editors/AutoCompleteEditor.vue
ui/src/forms/editors/index.ts
ui/src/forms/index.ts
ui/src/styles/app.scss
ui/src/styles/multiselect.scss
yarn.lock

My SPARQL query has some issues and I'm going to need help to fix it.
Addresses #442

feat: add dimension metadata unit

---

apis/core/lib/domain/dimension/DimensionMetadata.ts
apis/core/lib/domain/dimension/DimensionMetadataCollection.ts
apis/core/lib/domain/dimension/update.ts
apis/core/lib/domain/identifiers.ts
apis/core/lib/domain/queries/cube-project.ts
apis/core/test/domain/dimension/update.test.ts
apis/core/test/support/clownface.ts
cli/test/lib/commands/publish.test.ts
e2e-tests/dimension-metadata/update.hydra
packages/core/namespace.ts
packages/model/DimensionMetadata.ts
packages/testing/lib/chaiShapeMatcher.ts

Implements data structure changes proposed in #458 
* `prov:Dictionary` created when `Nominal` or `Ordinal` scale is set
* removed when it is set to anything else or removed

Initialise dimension mapping resource

---

apis/core/bootstrap/shapes/dataset.ts
ui/src/forms/FormObject.vue
ui/src/forms/editors/SelectEditor.vue
yarn.lock

feat: get publisher from open-data

---

apis/core/hydra/csv-source.ttl
apis/core/lib/handlers/csv-source.ts
e2e-tests/csv-source/delete.hydra
e2e-tests/csv-source/get-csv.hydra
packages/core/namespace.ts
ui/src/api/index.ts
ui/src/api/mixins/CSVSource.ts
ui/src/components/CsvSourceMapping.vue
ui/src/store/modules/project.ts
ui/src/store/serializers.ts

Allow the download of uploaded CSVs

feat: download csv

---

ui/src/api/index.ts
ui/src/components/CsvSourceMapping.vue
ui/src/store/modules/project.ts

These actions are starting to pile up and are not used everyday. Let's move them in a dropdown menu.
I also refactored the "download CSV" code a bit.

Move CSV source buttons in dropdown

---

ui/src/components/HydraOperationForm.vue
ui/src/forms/FormObject.vue
ui/tests/e2e/specs/project-mapping.spec.ts

Loading indicators everywhere is not great... but it's better than nothing at all

Improve form loading state

---

.github/workflows/releases.yaml

More meaningful commit and PR titles for the release automation

ci: release titles

---

apis/core/lib/domain/job/create.ts
apis/core/test/domain/job/create.test.ts
cli/lib/commands/publish.ts
cli/lib/commands/transform.ts
cli/lib/cube.ts
cli/lib/hydra-cache.ts
cli/lib/output-mapper.ts
cli/package.json
cli/pipelines/main.ttl
cli/pipelines/publish.ttl
cli/test/lib/output-mapper.test.ts
fuseki/sample-ubd.trig
packages/model/Job.ts
typings/barnard59-base/index.d.ts

Apply dimension mapping in the transform pipeline
fix #455

feat: pipeline applies dimension mappings

---

README.md

docs: describe release management

---

.changeset/lemon-vans-share.md
.changeset/strong-parrots-fix.md
.changeset/witty-lions-look.md
apis/core/bootstrap/shapes/dataset.ts
e2e-tests/dataset/update.hydra

feat: cube metadata changes

---

.github/workflows/releases.yaml

use GitHub app in changeset PR

---

apis/core/hydra/dimension-metadata.ttl
apis/core/lib/domain/column-mapping/create.ts
apis/core/lib/domain/column-mapping/delete.ts
apis/core/lib/domain/column-mapping/update.ts
apis/core/lib/domain/queries/dimension-metadata.ts
apis/core/lib/domain/table/delete.ts
apis/core/lib/domain/table/update.ts
apis/core/lib/handlers/dimension.ts
apis/core/test/domain/column-mapping/create.test.ts
apis/core/test/domain/column-mapping/delete.test.ts
apis/core/test/domain/column-mapping/update.test.ts
apis/core/test/domain/dimension-mapping/update.test.ts
apis/core/test/domain/table/create.test.ts
apis/core/test/domain/table/delete.test.ts
apis/core/test/domain/table/update.test.ts
apis/managed-dimensions/test/lib/domain/managed-dimensions.test.ts
e2e-tests/dimension-mapping/update.hydra
e2e-tests/dimension-metadata/get.hydra
fuseki/managed-dimensions.trig
fuseki/sample-ubd.trig
ui/src/components/CubePreviewDimension.vue
ui/src/store/serializers.ts
ui/src/views/DimensionMapping.vue

This adds `cc:managedDimension` property to mapped dimensions in the metadata collection

feat: include managed dimension URIs in metadata collection

---

.changeset/selfish-keys-shop.md
ui/src/store/modules/project.ts

fix(ui): CSV upload with special chars in file name

---

apis/core/lib/domain/dimension-mapping/update.ts
apis/core/test/domain/dimension-mapping/update.test.ts

Removing the mapped dimension currently causes an error. This PR fixes that.

fix: allow unmapping dimension

---

.changeset/calm-icons-count.md
.changeset/tidy-months-jam.md
apis/core/lib/domain/queries/dimension-metadata.ts
apis/core/lib/handlers/dimension.ts
apis/managed-dimensions/index.ts
cli/lib/output-mapper.ts

Run a second query to fetch dimension labels

fix: SERVICE breaks dimension query

---

.changeset/wild-seas-hear.md

Add missing changeset

---

.changeset/polite-kangaroos-destroy.md
ui/src/components/NavBar.vue

feat(ui): add link to documentation wiki

---

apis/core/bootstrap/shapes/dataset.ts
apis/core/bootstrap/shapes/dimension.ts

Various changes on the Metadata Fields [WIP]

---

.changeset/unlucky-crabs-matter.md

On second thought I guess this should be a minor

build: tweak changelog entry

---

.changeset/eleven-hotels-remember.md
cli/lib/toCubeShape/Dimension.js

fix(cli): do not generated sh:in for xsd:int dimension

---

.changeset/polite-birds-dream.md
.changeset/strange-coins-wonder.md
apis/core/bootstrap/shapes/cube-project.ts
apis/core/lib/domain/cube-projects/create.ts
apis/core/lib/domain/cube-projects/queries.ts
apis/core/lib/domain/cube-projects/update.ts
apis/core/lib/domain/dimension/update.ts
apis/core/test/domain/cube-projects/create.test.ts
apis/core/test/domain/cube-projects/queries.test.ts
apis/core/test/domain/cube-projects/update.test.ts
apis/core/test/domain/dimension/update.test.ts
cli/test/lib/commands/publish.test.ts
e2e-tests/csv-source/delete.hydra
e2e-tests/csv-source/get-csv.hydra
e2e-tests/csv-source/upload.hydra
e2e-tests/cube-projects/create.hydra
e2e-tests/cube-projects/delete.hydra
fuseki/sample-ubd.trig
ui/tests/e2e/specs/project-mapping.spec.ts

Prevent duplicate cube

---

packages/model/DimensionMetadata.ts
ui/src/components/CubePreviewDimension.vue
ui/src/components/DataKindIcon.vue
ui/src/store/serializers.ts

Part of #493 
Shows an icon for `dataKind`.

feat: display icon for dataKind

---

.changeset/tiny-dots-destroy.md
ui/src/components/JobForm.vue

fix(ui): wrong wording in toast when starting job

---

.changeset/shaggy-suits-provide.md
cli/lib/validation.ts
cli/package.json
cli/pipelines/main.ttl
fuseki/sample-ubd.trig
typings/rdf-validate-datatype/index.d.ts
yarn.lock

feat(pipeline): validate datatype of produced quads

---

.changeset/fast-students-happen.md
ui/src/views/DimensionMapping.vue

Adjust width of side-pane when mapping dimension to shared dimension
based on content.

fix(ui): adjust dimension mapping pane width

---

.changeset/eleven-dingos-breathe.md
ui/src/components/HydraOperationForm.vue
ui/src/components/JobForm.vue
ui/src/components/LiteralColumnMappingForm.vue
ui/src/views/CubeMetadataEdit.vue
ui/src/views/CubeProjectCreate.vue
ui/src/views/CubeProjectEdit.vue
ui/src/views/DimensionEdit.vue
ui/src/views/DimensionMapping.vue
ui/src/views/SharedDimensionCreate.vue
ui/src/views/SharedDimensionTermCreate.vue
ui/src/views/SharedDimensionTermEdit.vue
ui/src/views/SourceEdit.vue
ui/src/views/TableCreate.vue
ui/src/views/TableEdit.vue

This ensures that when "Cancel" is clicked on a form, it does discarded
fixes #336

fix: clone form resource

---

.changeset/chilly-dancers-talk.md
.changeset/khaki-falcons-sparkle.md
.changeset/tidy-masks-complain.md
apis/shared-dimensions/bootstrap/shapes.ts
apis/shared-dimensions/hydra/index.ttl
apis/shared-dimensions/lib/domain/shared-dimension.ts
apis/shared-dimensions/lib/handlers/shared-dimension.ts
apis/shared-dimensions/lib/namespace.ts
apis/shared-dimensions/lib/shapes/index.ts
apis/shared-dimensions/lib/shapes/shared-dimension.ts
apis/shared-dimensions/package.json
apis/shared-dimensions/test/lib/domain/managed-dimension.test.ts
apis/shared-dimensions/test/lib/shapes/index.test.ts
e2e-tests/shared-dimensions/term-set.hydra
ui/src/router/index.ts
ui/src/views/SharedDimension.vue
ui/src/views/SharedDimensionEdit.vue
yarn.lock

Editing shared dimensions

---

.changeset/thirty-bikes-clean.md
.local.env
apis/core/bootstrap/lib/query.ts
apis/core/lib/domain/queries/resources-types.ts
apis/core/test/domain/queries/resources-types.test.ts
packages/core/env.ts

Depends on https://gitlab.ldbar.ch/vshn/gitops-prod/-/merge_requests/257

fix: could not save form with external terms which do not dereference

---

.changeset/honest-trainers-nail.md
apis/shared-dimensions/lib/shapes/shared-dimension-term.ts
ui/package.json
ui/src/components/HydraOperationForm.vue
ui/src/components/HydraRawRdfForm.vue
ui/src/styles/utilities.scss
ui/src/views/SharedDimensionTermEdit.vue
yarn.lock

Add arbitrary data on shared dimension term

---

.changeset/cold-oranges-lick.md
ui/src/forms/editors/PropertyInput.vue

fix(ui): form submit on autocomplete selection

---

.changeset/witty-snakes-clap.md
apis/shared-dimensions/lib/shapes/shared-dimension.ts
ui/src/components/HydraOperationFormWithRaw.vue
ui/src/components/HydraRawRdfForm.vue
ui/src/views/CubeMetadataEdit.vue
ui/src/views/SharedDimensionEdit.vue
ui/src/views/SharedDimensionTermEdit.vue

One issue for the cube metadata: the data contains all sorts of stuff that we shouldn't probably edit (resource labels, generated shape, etc.). Not sure what to do about that.

Ability to edit shared dimension or cube metadata as raw RDF

---

.changeset/sour-weeks-reflect.md
apis/core/lib/csvw-builder/uriTemplateParser.ts

fix: escaping issue for CSV columns

---

.changeset/silver-seahorses-fry.md
apis/core/lib/domain/csv-source/upload.ts

fix(api): ensure s3 link is properly encoded URI

---

.changeset/breezy-planes-knock.md
cli/lib/toCubeShape/Dimension.js

fix: incorrect import broke pipelines

---

.changeset/nasty-plants-juggle.md
apis/core/lib/domain/csv-source/replace.ts
apis/core/test/domain/csv-source/replace.test.ts
ui/src/components/CsvSourceMapping.vue

#639 
Remove any previous parsing error when replacing the CSV file of a source.

Remove any previous parsing error when replacing the CSV file of a source

---

.changeset/funny-cycles-crash.md
apis/core/bootstrap/shapes/dimension.ts
packages/model/DimensionMetadata.ts
ui/src/components/CubePreview.vue
ui/src/store/serializers.ts

#672 
Adds dimension type on dimension metadata shape + changes cube preview based on that.

Dimension type

---

.changeset/spotty-dots-obey.md
cli/lib/metadata.ts
cli/test/lib/commands/publish.test.ts

Adds `rdf:type cube:SharedDimension` when cube is being published
closes #671

feat(cli): cube:SharedDimension

---

.changeset/loud-ravens-retire.md
cli/lib/cube.ts
cli/lib/metadata.ts
cli/pipelines/publish.ttl
cli/test/lib/commands/publish.test.ts
cli/test/lib/cube.test.ts
fuseki/sample-ubd.trig

feat(cli): add schema:sameAs to versioned concepts

---

.changeset/afraid-yaks-pay.md
apis/core/lib/domain/queries/cube-data.ts
apis/core/lib/handlers/cube-data.ts
apis/core/lib/query-client.ts
ui/src/components/CubePreview.vue
ui/src/components/CubePreviewValue.vue
ui/src/views/ResourcePreview.vue

fix: previews of shared terms

---

.changeset/thick-feet-compare.md
ui/src/api/mixins/JobCollection.ts
ui/src/components/JobIcon.vue
ui/src/components/TransformJobButton.vue
ui/src/store/modules/project.ts
ui/src/store/serializers.ts
ui/src/views/CubeProject.vue

Button for import job

---

.changeset/seven-plants-explain.md
cli/lib/commands/publish.ts
cli/lib/cube.ts
cli/lib/metadata.ts
cli/lib/variables.ts
cli/test/lib/commands/publish.test.ts

* track dimensions whose objects are versioned
* add `schema:version` to their Property Shape in cube constraint

feat(cli): dimension version annotation

---

.local.env
apis/core/lib/domain/cube-projects/create.ts
apis/core/lib/domain/cube-projects/queries.ts
apis/core/lib/domain/cube-projects/update.ts
apis/core/lib/domain/organization/query.ts
apis/core/test/domain/cube-projects/create.test.ts
apis/core/test/domain/cube-projects/queries.test.ts
apis/core/test/domain/cube-projects/update.test.ts
apis/core/test/domain/organization/query.test.ts
cli/test/lib/commands/import.test.ts
e2e-tests/cube-projects/create-invalid.hydra
fuseki/sample-px.trig

As much as sympathise with the suggestion to simplify the patterns to cross check cube identifiers, I think it's better not to materialise the CSV project's cube URI.

Import unique cube

---

.changeset/gorgeous-oranges-jump.md
ui/src/views/DimensionEdit.vue

re #740 
The form needs to be populated with deep graph including blank nodes

fix(ui): load CBD of dimension meta into form when editing

---

.changeset/fast-doors-grab.md
cli/package.json
yarn.lock

Not convinced an integration test is necessary

fix: set datatype of default csvw values

---

.changeset/eighty-glasses-double.md
.changeset/fast-needles-rule.md
apis/core/bootstrap/shapes/dimension.ts
apis/core/lib/domain/dimension-mapping/DimensionMapping.ts
apis/core/lib/domain/dimension-mapping/update.ts
apis/shared-dimensions/hydra/index.ttl
apis/shared-dimensions/lib/domain/shared-dimensions.ts
apis/shared-dimensions/lib/handlers/shared-dimensions.ts
apis/shared-dimensions/package.json
apis/shared-dimensions/test/lib/domain/managed-dimensions.test.ts
e2e-tests/dimension-mapping/update.hydra
e2e-tests/shared-dimensions/terms-filtered.hydra
e2e-tests/shared-dimensions/terms-only-valid.hydra
fuseki/shared-dimensions.trig
packages/core/namespace.ts
yarn.lock

First step towards #742 
This PR adds a search parameter to the terms URL template so that we can filter them by their names

feat: filtering shared dimension terms

---

.changeset/sour-rivers-drive.md
ui/src/views/SharedDimension.vue
ui/src/views/SharedDimensionTermEdit.vue

Nothing fancy, I just added a column in the table.

feat(ui): display shared dimension terms URI

---

.changeset/green-cheetahs-beam.md
ui/src/components/auth/SignOutButton.vue

This is an attempt at fixing cookies piling up over time.

fix(ui): clear stale OIDC cookies on logout

---

fuseki/sample-ubd.trig

chore: incorrect datatime in sample

---

.changeset/few-mice-remain.md
.changeset/hip-moons-clap.md
apis/core/bootstrap/organizations.ts
apis/core/lib/domain/dataset/update.ts
apis/core/test/domain/dataset/update.test.ts
packages/core/namespace.ts

Add lindas contact point and query URIs to dataset

---

.changeset/red-pots-fry.md
apis/core/hydra/projects.ttl
apis/core/lib/domain/cube-projects/export.ts
apis/core/lib/handlers/cube-projects.ts
apis/core/package.json
apis/core/test/domain/cube-projects/create.test.ts
apis/core/test/domain/cube-projects/export.test.ts
e2e-tests/cube-projects/create.hydra
e2e-tests/cube-projects/export.hydra
fuseki/sample-ubd.trig
packages/core/namespace.ts
packages/model/Project.ts
packages/model/lib/Link.ts
ui/package.json
ui/src/components/DownloadButton.vue
ui/src/views/CubeProjectEdit.vue
yarn.lock

Existing data will require migration to add the `cc:export` link:
```sparql
INSERT {
GRAPH ?project {
?project cc:export ?export
}
} WHERE {
GRAPH ?project {
?project a cc:CubeProject .
BIND ( IRI(CONCAT(STR(?project), '/export')) as ?export )
}
}
```

Exporting project

---

.changeset/afraid-swans-repair.md
apis/core/bootstrap/organizations.ts

Add SFA and SFOE organizations

---

.changeset/shiny-books-count.md
apis/core/bootstrap/shapes/dataset.ts

feat: add language for opendata.swiss keywords

---

.changeset/good-hairs-hope.md
cli/lib/validation.ts
cli/package.json

feat: improve pipeline datatype validation message

---

.changeset/heavy-chicken-smoke.md
apis/core/bootstrap/shapes/dataset.ts

Closes #923
This will require migrating existing data: `dcterms:license` -> `dcterms:rights`. @tpluscode can you help me with that?

Add opendata.swiss legal basis field

---

.changeset/silly-hats-beg.md
apis/core/lib/domain/dimension/update.ts
apis/core/test/domain/cube-projects/export.test.ts
fuseki/sample-ubd.trig
packages/core/namespace.ts
packages/model/DimensionMetadata.ts
ui/src/components/CubePreview.vue
ui/src/views/CubeDesigner.vue
yarn.lock

The moves the piece of code to determine that there is no measure dimension to the code which saves dimension metadata and updates the error accordingly

feat: calculate "no measure dimension" error on the API

---

.changeset/curvy-peas-wink.md
.lando.yml
apis/core/lib/domain/job/transformJob.ts
apis/core/lib/domain/job/update.ts
apis/core/package.json
fuseki/sample-ubd.trig
packages/model/Dataset.ts
packages/model/Job.ts
yarn.lock

This will create a warning about missing values for dimensions. There is only one warning with nested `schema:additionalProperty` for each affected dimension. Here's an example from a project rom INT (note that blank node will not be used in actual code)
```turtle
<https://int.cube-creator.lindas.admin.ch/cube-project/test-import-csv-from-url-w629nyz4dq1/dataset> 
schema:error [
schema:identifier "MissingObservationValues" ;
schema:description "There are observation values missing for some dimensions" ;
schema:additionalProperty [
schema:name "Dimension" ;
schema:identifier <https://culture.ld.admin.ch/sfa/test_import_csv_from_url/bemerkung> ;
schema:value 4857 ;
], [
schema:name "Dimension" ;
schema:identifier <https://culture.ld.admin.ch/sfa/test_import_csv_from_url/noga-code> ; …
```

Undefined values warning

---

.changeset/tricky-zebras-trade.md
ui/src/components/SharedDimensionTermLink.vue
ui/src/views/SharedDimension.vue

feat: replace shared term URI with link button

---

.changeset/strange-mayflies-protect.md
apis/core/bootstrap/shapes/table.ts
cli/lib/pipeline.ts
ui/src/components/CsvSourceMapping.vue
ui/tests/e2e/specs/project-mapping.spec.ts

Rename "observation" to "cube" table in more places in the UI

---

cli/test/lib/commands/publish.test.ts
cli/test/lib/commands/transform.test.ts
cli/test/lib/commands/unlist.test.ts

I have been wondering why for some time the coverage numbers have been deceasing in `cli` 🙈

Reenable cli tests

---

.changeset/shiny-icons-visit.md
apis/core/bootstrap/shapes/dataset.ts
packages/core/namespace.ts

Will require a query to migrate existing datasets.

feat: use EU frequencies instead of dublin core

---

.changeset/short-lions-beam.md
apis/core/bootstrap/shapes/dataset.ts
ui/src/forms/editors/TagsWithLanguageEditor.vue
ui/src/forms/editors/index.ts
ui/src/forms/matchers.ts
ui/src/forms/metadata.ts

Instead of having to create one entry per keyword, we have one field per language, with multiple keywords in the same field. It is much faster to edit.

Better dataset keywords input

---

.github/workflows/releases.yaml

Running changesets from master branch will soon stop working

ci: ping changesets

---

.changeset/smooth-badgers-beg.md
apis/core/lib/domain/column-mapping/update.ts
apis/core/test/domain/column-mapping/update.test.ts

fix: transformation failing after changing mapped property

---

.changeset/sixty-kangaroos-camp.md
ui/src/components/CubePreview.vue

fix(ui): do not request observations if page <= 0

---

apis/core/bootstrap/organizations.ts

Please double check, it was not linted. Entry on VSHN side is asked already. It should go to INT early next week.

chore: Add new organisation

---

.changeset/angry-vans-roll.md
apis/core/bootstrap/shapes/dimension.ts
apis/core/lib/domain/dimension-mapping/DimensionMapping.ts
apis/core/lib/domain/dimension-mapping/update.ts
apis/core/lib/handlers/dimension-mapping.ts
apis/core/package.json
apis/shared-dimensions/hydra/index.ttl
apis/shared-dimensions/lib/domain/shared-dimensions.ts
apis/shared-dimensions/lib/handlers/shared-dimensions.ts
apis/shared-dimensions/test/lib/domain/managed-dimensions.test.ts
ui/src/components/CubePreviewDimension.vue
ui/src/store/serializers.ts
yarn.lock

Depends on https://github.com/zazuko/hydra-box/pull/100

Map multiple shared dimensions

---

.changeset/perfect-donuts-crash.md
cli/lib/loadCube.ts
cli/lib/publish/upload.ts

The check of curl exit code was incorrect (compare with `if (exit.status)` in upload.ts.

fix: publish apears to fail to download cube

---

.changeset/great-pans-agree.md
apis/shared-dimensions/bootstrap/shapes.ts
apis/shared-dimensions/hydra/index.ttl
apis/shared-dimensions/lib/domain/hierarchies.ts
apis/shared-dimensions/lib/domain/resource.ts
apis/shared-dimensions/lib/domain/shared-dimension.ts
apis/shared-dimensions/lib/handlers/hierarchies.ts
apis/shared-dimensions/lib/namespace.ts
apis/shared-dimensions/lib/shapes/hierarchy.ts
apis/shared-dimensions/lib/shapes/index.ts
apis/shared-dimensions/package.json
ui/src/views/HierarchyCreate.vue

Turns out that I forgot to actually implement the `POST` handler to create a hierarchy

fix: saving new hierarchy

---

.changeset/proud-rats-rhyme.md
ui/src/forms/editors/DictionaryTableEditor.vue

The filtering algorithm is very naïve at the moment: lowercase + startsWith. We can implement something more complex if needed.

feat(ui): add simple text filter for dimension mapping values

---

.changeset/twenty-tools-tease.md
apis/core/bootstrap/shapes/column-mapping.ts
apis/core/bootstrap/shapes/dataset.ts
apis/core/bootstrap/shapes/dimension.ts
apis/core/bootstrap/shapes/table.ts

@tpluscode can you please finish this PR with creating the necessary tabs apis/core/bootstrap/shapes/column-mapping.ts
* main: Cube Metadata
* otab: Opendata.swiss
* atab: About
I tried to translate it over from the shared dimensions, but as is a different style of defining the shapes I failed.

clean-up and rearrange of some ui fields.

---

.changeset/polite-ties-pretend.md
ui/src/App.vue

This got broken when porting to Vue 3

fix(ui): authentication error handling broken

---

package.json
ui/package.json
yarn.lock

This came quicker than I expected :)

Revert temporary clownface resolution

---

.changeset/nice-snakes-grow.md
.changeset/sweet-boats-turn.md
apis/core/lib/domain/cube-projects/export.ts
apis/core/test/domain/cube-projects/export.test.ts
fuseki/sample-ubd.trig
ui/src/components/CsvUploadForm.vue
ui/src/views/CSVReplace.vue

Two improvements for external CSVs:

Improve external CSVs

---

.changeset/eight-papayas-hide.md
.changeset/twenty-singers-accept.md
apis/core/bootstrap/shapes/dimension.ts
apis/core/lib/domain/observations/index.ts
cli/shapes.ttl
packages/core/namespace.ts
packages/core/package.json
ui/src/forms/decorators/dimensionMetaHierarchySynchronizer.ts
yarn.lock

I think it's high time to get our act together and use correct vocabulary terms
I imported a new package which exports typed namespace builders of `https://cube.link` and `https://cube.link/meta/`. This will help expose discrepancies between what we do here and the actual vocabs

Vocabs cleanup

---

.github/workflows/setup-env/action.yml
e2e-tests/install-lando.sh
e2e-tests/start-lando.sh

https://github.com/tpluscode/action-setup-lando

ci: remove boilerplate to set up lando

---

.changeset/old-camels-return.md
.changeset/slow-ducks-turn.md
apis/core/bootstrap/shapes/jobs.ts
cli/lib/commands/timeoutJobs.ts
cli/lib/job.ts

Turns out it was SHACL validation on server

Timeout failing

---

.changeset/few-shirts-double.md
apis/core/bootstrap/organizations.ts

We need to add this new profile to Cube Creator

feat: add ofcom profile

---

.changeset/tall-worms-cry.md
ui/package.json
ui/src/customElements/FormObject.ts
ui/src/customElements/FormProperty.ts
ui/src/forms/index.ts
ui/src/forms/validation.ts
yarn.lock

Not perfect but at least some field will start showing inline errors
Problematic cases include nested forms and dynamic, conditional fields. For those it's not that easy to figure out that a given error should be rendered where
https://user-images.githubusercontent.com/588128/230398895-92dc54fc-e72b-4a2d-b2bd-a41c4ca66a61.mp4

feat: inline shacl violations

---

.changeset/tame-keys-push.md
.lando.yml
ui/package.json
ui/src/forms/editors/DatePickerEditor.vue
ui/src/forms/editors/DateTimePickerEditor.vue
yarn.lock

https://user-images.githubusercontent.com/588128/234010092-d927a954-485c-4ecf-9762-e98e46e99a4f.mp4

Editable calendar

---

.changeset/eighty-geckos-burn.md
apis/core/lib/domain/job/update.ts
apis/core/test/domain/job/update.test.ts
cli/lib/metadata.ts
cli/test/lib/commands/publish.test.ts

should fix https://github.com/zazuko/cube-creator/issues/1502

Date published

---

.changeset/cool-grapes-rush.md
apis/core/bootstrap/organizations.ts

Hey Zazuko
Ambrogio has asked me to create a publishing profile for BLW (Foag).
I also asked VSHN to give permission to write to a BLW-Cube-graph (not the one used by pipelines).
Please have a quick look if my changes make sense.
Thank you :)

Update organizations (Foag) .ts
